<?php

namespace App\Services;

use App\Models\DocumentDraft;
use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\IOFactory;
use PhpOffice\PhpWord\Style\Font;
use PhpOffice\PhpWord\SimpleType\Jc;
use Illuminate\Support\Facades\Storage;

class DocxExportService
{
    /**
     * Export draft to DOCX with proper formatting
     */
    public function exportToDocx(DocumentDraft $draft): string
    {
        $phpWord = new PhpWord();
        
        // Set document properties
        $properties = $phpWord->getDocInfo();
        $properties->setCreator(config('app.name'));
        $properties->setCompany(config('app.name'));
        $properties->setTitle($draft->title);
        $properties->setDescription('Generated by AI Document Paraphrasing System');
        $properties->setCategory('Dokumen Perizinan');
        $properties->setLastModifiedBy($draft->creator->name);
        $properties->setCreated(time());
        $properties->setModified(time());

        // Define styles
        $this->defineStyles($phpWord);

        // Add cover page
        $this->addCoverPage($phpWord, $draft);

        // Add metadata page
        $this->addMetadataPage($phpWord, $draft);

        // Add table of contents (placeholder)
        $this->addTableOfContents($phpWord);

        // Add main content
        $this->addMainContent($phpWord, $draft);

        // Add signature page
        $this->addSignaturePage($phpWord, $draft);

        // Save to storage
        $fileName = str_replace(' ', '_', $draft->title) . '_' . time() . '.docx';
        $filePath = 'exports/' . $fileName;
        $fullPath = storage_path('app/' . $filePath);

        // Create directory if not exists
        if (!file_exists(dirname($fullPath))) {
            mkdir(dirname($fullPath), 0755, true);
        }

        // Save document
        $objWriter = IOFactory::createWriter($phpWord, 'Word2007');
        $objWriter->save($fullPath);

        return $filePath;
    }

    /**
     * Define document styles
     */
    protected function defineStyles(PhpWord $phpWord): void
    {
        // Title style
        $phpWord->addTitleStyle(1, [
            'name' => 'Times New Roman',
            'size' => 18,
            'bold' => true,
            'color' => '000000',
        ], [
            'alignment' => Jc::CENTER,
            'spaceAfter' => 240,
        ]);

        // Heading 1
        $phpWord->addTitleStyle(2, [
            'name' => 'Times New Roman',
            'size' => 14,
            'bold' => true,
            'color' => '000000',
        ], [
            'spaceBefore' => 240,
            'spaceAfter' => 120,
        ]);

        // Heading 2
        $phpWord->addTitleStyle(3, [
            'name' => 'Times New Roman',
            'size' => 12,
            'bold' => true,
            'color' => '000000',
        ], [
            'spaceBefore' => 120,
            'spaceAfter' => 60,
        ]);

        // Normal paragraph
        $phpWord->addParagraphStyle('Normal', [
            'alignment' => Jc::BOTH,
            'spaceBefore' => 0,
            'spaceAfter' => 120,
            'lineHeight' => 1.5,
            'indentation' => ['firstLine' => 720], // 1cm indent
        ]);

        // Quote/highlight style
        $phpWord->addParagraphStyle('Quote', [
            'alignment' => Jc::BOTH,
            'spaceBefore' => 120,
            'spaceAfter' => 120,
            'indentation' => ['left' => 720, 'right' => 720],
        ]);
    }

    /**
     * Add cover page
     */
    protected function addCoverPage(PhpWord $phpWord, DocumentDraft $draft): void
    {
        $section = $phpWord->addSection([
            'marginLeft' => 1440,
            'marginRight' => 1440,
            'marginTop' => 1440,
            'marginBottom' => 1440,
        ]);

        // Add vertical spacing
        $section->addTextBreak(5);

        // Title
        $section->addTitle($draft->title, 1);

        // Subtitle
        $section->addText(
            strtoupper(str_replace('_', ' ', $draft->template->permit_type)),
            ['size' => 12, 'bold' => true],
            ['alignment' => Jc::CENTER, 'spaceAfter' => 480]
        );

        // Project info
        $section->addTextBreak(3);
        $section->addText(
            'Proyek: ' . $draft->project->name,
            ['size' => 11],
            ['alignment' => Jc::CENTER]
        );

        if ($draft->project->client) {
            $section->addText(
                'Klien: ' . $draft->project->client->name,
                ['size' => 11],
                ['alignment' => Jc::CENTER]
            );
        }

        // Date
        $section->addTextBreak(5);
        $section->addText(
            now()->format('d F Y'),
            ['size' => 11, 'bold' => true],
            ['alignment' => Jc::CENTER]
        );

        // Add page break
        $section->addPageBreak();
    }

    /**
     * Add metadata/info page
     */
    protected function addMetadataPage(PhpWord $phpWord, DocumentDraft $draft): void
    {
        $section = $phpWord->addSection();

        $section->addTitle('INFORMASI DOKUMEN', 2);

        // Create table for metadata
        $table = $section->addTable([
            'borderSize' => 6,
            'borderColor' => '000000',
            'cellMargin' => 80,
        ]);

        $this->addTableRow($table, 'Jenis Dokumen', strtoupper(str_replace('_', ' ', $draft->template->permit_type)));
        $this->addTableRow($table, 'Nomor Dokumen', $draft->project->code . '/' . $draft->id . '/' . now()->format('Y'));
        $this->addTableRow($table, 'Status', strtoupper($draft->status));
        $this->addTableRow($table, 'Proyek', $draft->project->name);
        
        if ($draft->project->client) {
            $this->addTableRow($table, 'Klien', $draft->project->client->name);
        }
        
        $this->addTableRow($table, 'Lokasi', $draft->project->location ?? '-');
        $this->addTableRow($table, 'Dibuat Oleh', $draft->creator->name);
        $this->addTableRow($table, 'Tanggal Dibuat', $draft->created_at->format('d F Y, H:i'));

        if ($draft->status === 'approved' && $draft->approver) {
            $this->addTableRow($table, 'Disetujui Oleh', $draft->approver->name);
            $this->addTableRow($table, 'Tanggal Disetujui', $draft->approved_at->format('d F Y, H:i'));
        }

        // AI Processing info
        if ($draft->aiLog) {
            $section->addTextBreak(1);
            $section->addTitle('INFORMASI PEMROSESAN AI', 3);
            
            $aiTable = $section->addTable([
                'borderSize' => 6,
                'borderColor' => '000000',
                'cellMargin' => 80,
            ]);
            
            $this->addTableRow($aiTable, 'Model AI', 'Google Gemini Flash');
            $this->addTableRow($aiTable, 'Total Token', number_format($draft->aiLog->total_tokens));
            
            if ($draft->aiLog->metadata && isset($draft->aiLog->metadata['duration_seconds'])) {
                $this->addTableRow($aiTable, 'Durasi Pemrosesan', round($draft->aiLog->metadata['duration_seconds'], 1) . ' detik');
            }
            
            $this->addTableRow($aiTable, 'Biaya', $draft->aiLog->cost > 0 ? '$' . number_format($draft->aiLog->cost, 6) : 'GRATIS');
        }

        $section->addPageBreak();
    }

    /**
     * Add table of contents placeholder
     */
    protected function addTableOfContents(PhpWord $phpWord): void
    {
        $section = $phpWord->addSection();
        $section->addTitle('DAFTAR ISI', 2);
        $section->addText(
            'Daftar isi akan diupdate otomatis ketika dokumen dibuka di Microsoft Word. Klik kanan pada area ini dan pilih "Update Field".',
            ['size' => 10, 'italic' => true, 'color' => '666666']
        );
        $section->addTOC(['size' => 11], ['tabLeader' => \PhpOffice\PhpWord\Style\TOC::TABLEADER_DOT]);
        $section->addPageBreak();
    }

    /**
     * Add main content
     */
    protected function addMainContent(PhpWord $phpWord, DocumentDraft $draft): void
    {
        $section = $phpWord->addSection();
        
        // Parse content into paragraphs
        $paragraphs = explode("\n\n", $draft->content);
        
        foreach ($paragraphs as $paragraph) {
            $paragraph = trim($paragraph);
            
            if (empty($paragraph)) {
                continue;
            }

            // Check if it's a heading (starts with ## or similar)
            if (preg_match('/^#{2,3}\s+(.+)$/', $paragraph, $matches)) {
                $level = substr_count($paragraph, '#') + 1; // H2 = level 2, H3 = level 3
                $section->addTitle(trim($matches[1]), $level);
            }
            // Check if it's a list item
            elseif (preg_match('/^[-•*]\s+(.+)$/', $paragraph, $matches)) {
                $section->addListItem(trim($matches[1]), 0, ['size' => 12]);
            }
            // Regular paragraph
            else {
                $section->addText(
                    $paragraph,
                    ['name' => 'Times New Roman', 'size' => 12],
                    'Normal'
                );
            }
        }

        $section->addPageBreak();
    }

    /**
     * Add signature page
     */
    protected function addSignaturePage(PhpWord $phpWord, DocumentDraft $draft): void
    {
        $section = $phpWord->addSection();
        
        $section->addTextBreak(2);
        
        // Disclaimer
        $section->addText(
            'Dokumen ini dihasilkan secara otomatis menggunakan sistem AI dan telah diverifikasi oleh pihak yang berwenang.',
            ['size' => 10, 'italic' => true],
            ['alignment' => Jc::CENTER]
        );
        
        $section->addTextBreak(3);
        
        // Signature
        // Fallback to project client address if explicit location is unavailable
        $location = $draft->project->client_address ?? 'Jakarta';
        $date = now()->format('d F Y');
        
        $section->addText(
            $location . ', ' . $date,
            ['size' => 12],
            ['alignment' => Jc::END]
        );
        
        $section->addText(
            config('app.name'),
            ['size' => 12, 'bold' => true],
            ['alignment' => Jc::END]
        );
        
        $section->addTextBreak(4);
        
        $signatureName = $draft->status === 'approved' && $draft->approver 
            ? $draft->approver->name 
            : $draft->creator->name;
            
        $section->addText(
            '( ' . $signatureName . ' )',
            ['size' => 12, 'bold' => true, 'underline' => 'single'],
            ['alignment' => Jc::END]
        );
    }

    /**
     * Helper: Add table row
     */
    protected function addTableRow($table, string $label, string $value): void
    {
        $table->addRow();
        $table->addCell(3000)->addText(
            $label,
            ['bold' => true, 'size' => 11]
        );
        $table->addCell(6000)->addText(
            $value,
            ['size' => 11]
        );
    }

    /**
     * Download DOCX file
     */
    public function downloadDocx(string $filePath): \Symfony\Component\HttpFoundation\BinaryFileResponse
    {
        $fullPath = storage_path('app/' . $filePath);
        
        if (!file_exists($fullPath)) {
            abort(404, 'File not found');
        }

        return response()->download($fullPath)->deleteFileAfterSend(true);
    }
}
