<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\InstitutionController;
use App\Http\Controllers\ProjectPaymentController;
use App\Http\Controllers\ProjectExpenseController;
use App\Http\Controllers\CashAccountController;
use App\Http\Controllers\GeneralTransactionController;
use App\Http\Controllers\BankReconciliationController;
use App\Http\Controllers\PermitTypeController;
use App\Http\Controllers\PermitTemplateController;
use App\Http\Controllers\ProjectPermitController;
use App\Http\Controllers\PermitController;
use App\Http\Controllers\Financial\OverviewController as FinancialOverviewController;
use App\Http\Controllers\Financial\InvoiceController as FinancialInvoiceController;
use App\Http\Controllers\Financial\PaymentScheduleController as FinancialPaymentScheduleController;
use App\Http\Controllers\Financial\ExpenseController as FinancialExpenseController;
use App\Http\Controllers\Financial\DirectIncomeController as FinancialDirectIncomeController;
use App\Http\Controllers\Financial\ExportController as FinancialExportController;
use App\Http\Controllers\ExportController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\PublicArticleController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\LocaleController;
use App\Http\Controllers\SitemapController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\Admin\PermitManagementController;
use App\Http\Controllers\Admin\RecruitmentController;
use App\Http\Controllers\Admin\ConsultationLeadController;
use App\Http\Controllers\RssFeedController;
use App\Http\Controllers\ProgrammaticSeoController;
use App\Http\Controllers\ServiceComparisonController;
use App\Http\Controllers\FaqAggregationController;
use App\Http\Controllers\PillarPageController;
use App\Http\Controllers\Admin\Seo\SeoScoresController;
use App\Http\Controllers\Admin\Seo\SeoReportsController;
use App\Http\Controllers\Admin\Seo\SeoCompetitorsController;
use App\Http\Controllers\Admin\Seo\SeoAbTestsController;
use App\Http\Controllers\Admin\Seo\SeoSearchConsoleController;
use App\Http\Controllers\Admin\Seo\SeoRefreshLogsController;
use App\Http\Controllers\Admin\Seo\SeoProgrammaticController;
use App\Http\Controllers\Admin\Seo\SeoPositionsController;
use App\Http\Controllers\Admin\Seo\SeoRankingAlertsController;

require __DIR__.'/admin/core.php';
require __DIR__.'/admin/operations.php';
require __DIR__.'/admin/settings_recruitment.php';
require __DIR__.'/admin/communications_seo_ai.php';
