<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Routing\Route as LaravelRoute;
use Illuminate\Support\Facades\Route;

class AdminRoutesAudit extends Command
{
    protected $signature = 'admin:routes-audit {--format=md : md|json}';

    protected $description = 'Audit admin routes, classify risk, and propose required permissions';

    public function handle(): int
    {
        $format = (string) $this->option('format');
        $routes = collect(Route::getRoutes()->getRoutes())
            ->filter(fn (LaravelRoute $route) => str_starts_with($route->uri(), 'admin/'));

        $rows = $routes
            ->map(fn (LaravelRoute $route) => $this->analyze($route))
            ->sortBy(['module', 'risk', 'uri'])
            ->values();

        if ($format === 'json') {
            $this->line(json_encode($rows->all(), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE));

            return self::SUCCESS;
        }

        $this->line('# Admin Routes Security Audit');
        $this->line('');
        $this->line('- Generated by `php artisan admin:routes-audit`');
        $this->line('- Scope: routes with URI prefix `admin/`');
        $this->line('');

        foreach ($rows->groupBy('module') as $module => $moduleRows) {
            $this->line('## '.$module);
            $this->line('');
            $this->line('| Method | URI | Name | Risk | Required permission | Missing permission middleware |');
            $this->line('|---|---|---|---:|---|---|');
            foreach ($moduleRows as $row) {
                $this->line('| '.$row['method'].' | '.$row['uri'].' | '.($row['name'] ?: '-').' | '.$row['risk'].' | '.($row['required_permission'] ?: '-').' | '.($row['missing_permission_middleware'] ? 'YES' : 'NO').' |');
            }
            $this->line('');
        }

        return self::SUCCESS;
    }

    private function analyze(LaravelRoute $route): array
    {
        $methods = array_values(array_diff($route->methods(), ['HEAD']));
        $method = $methods[0] ?? 'GET';
        $uri = $route->uri();
        $name = (string) ($route->getName() ?? '');
        $middleware = $route->gatherMiddleware();

        $module = $this->moduleFrom($name, $uri);
        $required = $this->requiredPermission($module, $method, $name, $uri);
        $risk = $this->riskFrom($module, $method, $name, $uri);

        $missingPermissionMiddleware = false;
        if ($required) {
            $needle = 'permission:'.$required;
            $missingPermissionMiddleware = ! in_array($needle, $middleware, true);
        }

        return [
            'method' => $method,
            'uri' => $uri,
            'name' => $name,
            'module' => $module,
            'risk' => $risk,
            'required_permission' => $required,
            'missing_permission_middleware' => $missingPermissionMiddleware,
        ];
    }

    private function moduleFrom(string $name, string $uri): string
    {
        $n = $name;
        if (str_starts_with($n, 'settings.')) {
            return 'Settings';
        }
        if (str_starts_with($n, 'admin.security.')) {
            return 'Security';
        }
        if (str_starts_with($n, 'admin.leads.')) {
            return 'Leads';
        }
        if (str_starts_with($n, 'admin.service-inquiries.')) {
            return 'Leads';
        }
        if (str_starts_with($n, 'admin.consultation-leads.')) {
            return 'Leads';
        }
        if (str_starts_with($n, 'admin.service-cost-requests.')) {
            return 'Leads';
        }
        if (str_starts_with($n, 'projects.')) {
            return 'Projects';
        }
        if (str_starts_with($n, 'tasks.')) {
            return 'Tasks';
        }
        if (str_starts_with($n, 'documents.')) {
            return 'Documents';
        }
        if (str_starts_with($n, 'institutions.')) {
            return 'Institutions';
        }
        if (str_starts_with($n, 'clients.')) {
            return 'Clients';
        }
        if (str_starts_with($n, 'invoices.')) {
            return 'Invoices';
        }
        if (str_starts_with($n, 'exports.')) {
            return 'Reports';
        }
        if (str_starts_with($n, 'reconciliations.')) {
            return 'Finances';
        }
        if (str_starts_with($n, 'cash-accounts.')) {
            return 'Finances';
        }
        if (str_starts_with($n, 'general-transactions.')) {
            return 'Finances';
        }
        if (str_starts_with($n, 'admin.jobs.') || str_starts_with($n, 'admin.applications.')) {
            return 'Recruitment';
        }
        if (str_starts_with($n, 'articles.') || str_starts_with($n, 'auto-post.') || str_starts_with($n, 'pexels.')) {
            return 'Content';
        }
        if (str_starts_with($n, 'admin.seo.')) {
            return 'SEO';
        }
        if (str_starts_with($n, 'admin.email-management.') || str_starts_with($n, 'admin.inbox.') || str_starts_with($n, 'admin.campaigns.') || str_starts_with($n, 'admin.subscribers.') || str_starts_with($n, 'admin.templates.') || str_starts_with($n, 'admin.email.')) {
            return 'Email';
        }
        if (str_starts_with($n, 'admin.ai-settings.')) {
            return 'AI';
        }

        if (str_contains($uri, 'ai-settings')) {
            return 'AI';
        }
        if (str_contains($uri, 'seo/')) {
            return 'SEO';
        }
        if (str_contains($uri, 'inbox') || str_contains($uri, 'email')) {
            return 'Email';
        }

        return 'Other';
    }

    private function requiredPermission(string $module, string $method, string $name, string $uri): ?string
    {
        $write = in_array($method, ['POST', 'PUT', 'PATCH', 'DELETE'], true);

        return match ($module) {
            'Security' => 'security.view',
            'AI' => 'ai.manage_settings',
            'Settings' => 'settings.manage',
            'Projects' => $write ? 'projects.edit' : 'projects.view',
            'Tasks' => $write ? 'tasks.edit' : 'tasks.view',
            'Documents' => $write ? 'documents.upload' : 'documents.view',
            'Institutions' => $write ? 'institutions.edit' : 'institutions.view',
            'Clients' => $write ? 'clients.edit' : 'clients.view',
            'Invoices' => $write ? 'invoices.edit' : 'invoices.view',
            'Finances' => $write ? 'finances.manage_accounts' : 'finances.view',
            'Content' => 'content.manage',
            'SEO' => 'content.manage',
            'Email' => 'email.manage',
            'Recruitment' => $write ? 'recruitment.manage' : 'recruitment.view',
            'Leads' => $write ? 'clients.edit' : 'clients.view',
            default => null,
        };
    }

    private function riskFrom(string $module, string $method, string $name, string $uri): string
    {
        $write = in_array($method, ['POST', 'PUT', 'PATCH', 'DELETE'], true);

        if (in_array($module, ['Settings', 'Security', 'AI'], true)) {
            return 'HIGH';
        }

        if (in_array($module, ['Finances', 'Invoices'], true)) {
            return $write ? 'HIGH' : 'MEDIUM';
        }

        if (in_array($module, ['Email', 'SEO', 'Content', 'Recruitment'], true)) {
            return $write ? 'HIGH' : 'MEDIUM';
        }

        if (in_array($module, ['Projects', 'Tasks', 'Documents', 'Clients', 'Institutions', 'Leads'], true)) {
            return $write ? 'MEDIUM' : 'LOW';
        }

        return $write ? 'MEDIUM' : 'LOW';
    }
}
