<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Programmatic SEO Configuration
    |--------------------------------------------------------------------------
    |
    | City + service combinations for automatic long-tail keyword page generation.
    | Each city has local context data used to create unique, valuable content.
    |
    */

    'enabled' => true,

    // Target cities/regions with industrial activity
    'cities' => [
        'karawang' => [
            'name' => 'Karawang',
            'province' => 'Jawa Barat',
            'slug' => 'karawang',
            'description' => 'Karawang merupakan kawasan industri terbesar di Indonesia dengan lebih dari 13.000 perusahaan di 11 kawasan industri, termasuk KIIC, Suryacipta, dan Karawang International Industrial City.',
            'industries' => ['manufaktur', 'otomotif', 'elektronik', 'tekstil', 'farmasi', 'makanan & minuman'],
            'industrial_zones' => ['KIIC', 'Suryacipta City of Industry', 'Karawang International Industrial City (KIIC)', 'Karawang New Industry City (KNIC)', 'Indotaisei Industrial Estate'],
            'population' => '2.4 juta',
            'key_regulations' => 'Perda Kabupaten Karawang tentang RTRW dan perizinan industri',
            'government_office' => 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu (DPMPTSP) Kabupaten Karawang',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Karawang',
        ],
        'bekasi' => [
            'name' => 'Bekasi',
            'province' => 'Jawa Barat',
            'slug' => 'bekasi',
            'description' => 'Bekasi adalah pusat industri di koridor timur Jakarta dengan kawasan industri besar seperti MM2100, Jababeka, dan Delta Silicon. Kota dan kabupaten Bekasi menampung ribuan perusahaan manufaktur.',
            'industries' => ['manufaktur', 'otomotif', 'kimia', 'elektronik', 'logistik'],
            'industrial_zones' => ['MM2100 Industrial Town', 'Jababeka Industrial Estate', 'Delta Silicon Industrial Park', 'Lippo Cikarang', 'Greenland International Industrial Center (GIIC)'],
            'population' => '3.1 juta (kota) + 3.8 juta (kabupaten)',
            'key_regulations' => 'Perda Kota/Kabupaten Bekasi tentang perizinan berusaha',
            'government_office' => 'DPMPTSP Kota Bekasi / DPMPTSP Kabupaten Bekasi',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Bekasi',
        ],
        'jakarta' => [
            'name' => 'Jakarta',
            'province' => 'DKI Jakarta',
            'slug' => 'jakarta',
            'description' => 'Jakarta sebagai ibukota negara merupakan pusat bisnis dan regulasi di Indonesia. Banyak perusahaan berkantor pusat di Jakarta dengan fasilitas produksi di daerah sekitarnya.',
            'industries' => ['jasa keuangan', 'teknologi', 'perdagangan', 'konstruksi', 'F&B', 'farmasi'],
            'industrial_zones' => ['Pulogadung Industrial Estate', 'Cakung Industrial Area', 'Sunter Industrial Area', 'Marunda Industrial Area'],
            'population' => '10.6 juta',
            'key_regulations' => 'Perda DKI Jakarta tentang lingkungan hidup dan penataan ruang',
            'government_office' => 'DPMPTSP Provinsi DKI Jakarta',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Jakarta',
        ],
        'tangerang' => [
            'name' => 'Tangerang',
            'province' => 'Banten',
            'slug' => 'tangerang',
            'description' => 'Tangerang adalah pusat industri di koridor barat Jakarta dengan berbagai kawasan industri yang menampung perusahaan multinasional dan lokal dari berbagai sektor.',
            'industries' => ['manufaktur', 'garmen', 'makanan & minuman', 'kimia', 'logistik'],
            'industrial_zones' => ['Jatake Industrial Estate', 'Millennium Industrial Estate', 'Cikupa Mas Industrial Estate', 'Tangerang International Industrial Estate'],
            'population' => '2.1 juta (kota) + 3.7 juta (kabupaten)',
            'key_regulations' => 'Perda Kota/Kabupaten Tangerang tentang perizinan lingkungan',
            'government_office' => 'DPMPTSP Kota Tangerang / DPMPTSP Kabupaten Tangerang',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Tangerang',
        ],
        'bogor' => [
            'name' => 'Bogor',
            'province' => 'Jawa Barat',
            'slug' => 'bogor',
            'description' => 'Bogor memiliki aktivitas industri yang berkembang pesat, terutama di wilayah Cibinong, Sentul, dan Cileungsi dengan fokus pada industri manufaktur dan pengolahan.',
            'industries' => ['manufaktur', 'makanan & minuman', 'farmasi', 'kertas & pulp', 'tekstil'],
            'industrial_zones' => ['Sentul Industrial Estate', 'Cileungsi Industrial Area', 'Gunung Putri Industrial Estate'],
            'population' => '1.1 juta (kota) + 5.9 juta (kabupaten)',
            'key_regulations' => 'Perda Kota/Kabupaten Bogor tentang pengelolaan lingkungan hidup',
            'government_office' => 'DPMPTSP Kota Bogor / DPMPTSP Kabupaten Bogor',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Bogor',
        ],
        'surabaya' => [
            'name' => 'Surabaya',
            'province' => 'Jawa Timur',
            'slug' => 'surabaya',
            'description' => 'Surabaya sebagai kota terbesar kedua di Indonesia merupakan pusat industri dan perdagangan di Jawa Timur dengan akses pelabuhan Tanjung Perak.',
            'industries' => ['manufaktur', 'perkapalan', 'logistik', 'makanan & minuman', 'petrokimia'],
            'industrial_zones' => ['Surabaya Industrial Estate Rungkut (SIER)', 'Maspion Industrial Estate', 'Pasuruan Industrial Estate Rembang (PIER)'],
            'population' => '2.9 juta',
            'key_regulations' => 'Perda Kota Surabaya tentang pengendalian pencemaran lingkungan',
            'government_office' => 'DPMPTSP Kota Surabaya',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Surabaya',
        ],
        'semarang' => [
            'name' => 'Semarang',
            'province' => 'Jawa Tengah',
            'slug' => 'semarang',
            'description' => 'Semarang adalah ibukota Jawa Tengah dengan kawasan industri yang berkembang di Genuk, Tugu, dan sekitarnya.',
            'industries' => ['manufaktur', 'tekstil', 'makanan & minuman', 'mebel', 'farmasi'],
            'industrial_zones' => ['Kawasan Industri Tugu', 'Kawasan Industri Genuk', 'Kawasan Industri Candi', 'Kawasan Industri Terboyo'],
            'population' => '1.7 juta',
            'key_regulations' => 'Perda Kota Semarang tentang izin lingkungan dan penataan ruang',
            'government_office' => 'DPMPTSP Kota Semarang',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Semarang',
        ],
        'bandung' => [
            'name' => 'Bandung',
            'province' => 'Jawa Barat',
            'slug' => 'bandung',
            'description' => 'Bandung dan sekitarnya merupakan pusat industri tekstil dan garmen terbesar di Indonesia, serta berkembang sebagai pusat teknologi dan startup.',
            'industries' => ['tekstil', 'garmen', 'teknologi', 'farmasi', 'makanan & minuman', 'kreatif'],
            'industrial_zones' => ['Kawasan Industri Majalaya', 'Kawasan Industri Rancaekek', 'Kawasan Industri Cimareme', 'Kawasan Industri Padalarang'],
            'population' => '2.5 juta (kota) + 3.8 juta (kabupaten)',
            'key_regulations' => 'Perda Kota/Kabupaten Bandung tentang pengelolaan lingkungan hidup',
            'government_office' => 'DPMPTSP Kota Bandung / DPMPTSP Kabupaten Bandung',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Bandung',
        ],
        'cikarang' => [
            'name' => 'Cikarang',
            'province' => 'Jawa Barat',
            'slug' => 'cikarang',
            'description' => 'Cikarang adalah kawasan industri terbesar di Asia Tenggara dengan lebih dari 5.000 perusahaan multinasional dari Jepang, Korea, Eropa, dan Amerika.',
            'industries' => ['otomotif', 'elektronik', 'manufaktur', 'kimia', 'komponen otomotif'],
            'industrial_zones' => ['Jababeka Industrial Estate', 'Delta Silicon Industrial Park', 'Lippo Cikarang', 'EJIP (East Jakarta Industrial Park)', 'Hyundai Engineering Industrial Park'],
            'population' => '800 ribu+',
            'key_regulations' => 'Mengikuti regulasi Kabupaten Bekasi untuk perizinan industri',
            'government_office' => 'DPMPTSP Kabupaten Bekasi (meliputi wilayah Cikarang)',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Cikarang',
        ],
        'purwakarta' => [
            'name' => 'Purwakarta',
            'province' => 'Jawa Barat',
            'slug' => 'purwakarta',
            'description' => 'Purwakarta berkembang sebagai kawasan industri alternatif dengan lokasi strategis antara Jakarta dan Bandung di jalur tol Cikampek.',
            'industries' => ['manufaktur', 'keramik', 'semen', 'tekstil', 'makanan & minuman'],
            'industrial_zones' => ['Kawasan Industri Bukit Indah', 'Kawasan Industri Jatiluhur'],
            'population' => '950 ribu',
            'key_regulations' => 'Perda Kabupaten Purwakarta tentang penataan ruang dan perizinan',
            'government_office' => 'DPMPTSP Kabupaten Purwakarta',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Purwakarta',
        ],
        'subang' => [
            'name' => 'Subang',
            'province' => 'Jawa Barat',
            'slug' => 'subang',
            'description' => 'Subang berkembang menjadi lokasi industri baru dengan hadirnya proyek Patimban dan kawasan industri di sepanjang koridor utara Jawa Barat.',
            'industries' => ['manufaktur', 'agro-industri', 'logistik', 'otomotif'],
            'industrial_zones' => ['Kawasan Industri Subang Smartpolitan', 'Patimban Industrial Area'],
            'population' => '1.6 juta',
            'key_regulations' => 'Perda Kabupaten Subang tentang investasi dan perizinan berusaha',
            'government_office' => 'DPMPTSP Kabupaten Subang',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Subang',
        ],
        'serang' => [
            'name' => 'Serang & Cilegon',
            'province' => 'Banten',
            'slug' => 'serang',
            'description' => 'Kawasan Serang dan Cilegon merupakan pusat industri berat di Banten, dengan industri baja (Krakatau Steel), petrokimia, dan berbagai industri pengolahan.',
            'industries' => ['baja', 'petrokimia', 'kimia', 'semen', 'energi', 'manufaktur'],
            'industrial_zones' => ['Krakatau Industrial Estate Cilegon (KIEC)', 'Modern Cikande Industrial Estate', 'Nikomas Gemilang Industrial Park'],
            'population' => '700 ribu (Serang) + 400 ribu (Cilegon)',
            'key_regulations' => 'Perda Kota Cilegon dan Kabupaten Serang tentang lingkungan hidup',
            'government_office' => 'DPMPTSP Kota Cilegon / DPMPTSP Kabupaten Serang',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Serang/Cilegon',
        ],
        'depok' => [
            'name' => 'Depok',
            'province' => 'Jawa Barat',
            'slug' => 'depok',
            'description' => 'Depok merupakan kota penyangga Jakarta dengan pertumbuhan usaha kecil menengah yang pesat, terutama di sektor jasa, perdagangan, dan industri ringan.',
            'industries' => ['perdagangan', 'jasa', 'makanan & minuman', 'konveksi', 'percetakan'],
            'industrial_zones' => ['Kawasan Industri Tugu Depok', 'Sentra Industri Cipayung'],
            'population' => '2.5 juta',
            'key_regulations' => 'Perda Kota Depok tentang perizinan berusaha dan lingkungan hidup',
            'government_office' => 'DPMPTSP Kota Depok',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Depok',
        ],
        'cirebon' => [
            'name' => 'Cirebon',
            'province' => 'Jawa Barat',
            'slug' => 'cirebon',
            'description' => 'Cirebon adalah kota pelabuhan dan pusat industri di pantai utara Jawa Barat dengan sektor rotan, batik, dan pengolahan makanan laut yang kuat.',
            'industries' => ['rotan', 'batik', 'pengolahan ikan', 'makanan & minuman', 'perdagangan'],
            'industrial_zones' => ['Kawasan Industri Plumbon', 'Kawasan Industri Mundu'],
            'population' => '330 ribu (kota) + 2.2 juta (kabupaten)',
            'key_regulations' => 'Perda Kota/Kabupaten Cirebon tentang pengelolaan lingkungan',
            'government_office' => 'DPMPTSP Kota Cirebon / DPMPTSP Kabupaten Cirebon',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Cirebon',
        ],
        'sukabumi' => [
            'name' => 'Sukabumi',
            'province' => 'Jawa Barat',
            'slug' => 'sukabumi',
            'description' => 'Sukabumi berkembang sebagai kawasan industri baru di selatan Jawa Barat dengan fokus pada industri manufaktur dan pengolahan hasil pertanian.',
            'industries' => ['manufaktur', 'agro-industri', 'tekstil', 'sepatu', 'makanan & minuman'],
            'industrial_zones' => ['Kawasan Industri Cikembar', 'Kawasan Industri Cicurug'],
            'population' => '340 ribu (kota) + 2.5 juta (kabupaten)',
            'key_regulations' => 'Perda Kabupaten Sukabumi tentang penataan ruang dan perizinan',
            'government_office' => 'DPMPTSP Kota Sukabumi / DPMPTSP Kabupaten Sukabumi',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Sukabumi',
        ],
        'solo' => [
            'name' => 'Solo (Surakarta)',
            'province' => 'Jawa Tengah',
            'slug' => 'solo',
            'description' => 'Solo atau Surakarta merupakan pusat industri batik, tekstil, dan mebel di Jawa Tengah dengan ekosistem UMKM yang sangat kuat.',
            'industries' => ['batik', 'tekstil', 'mebel', 'makanan & minuman', 'kerajinan'],
            'industrial_zones' => ['Kawasan Industri Palur', 'Kawasan Industri Gondangrejo', 'Kawasan Industri Jaten'],
            'population' => '520 ribu (kota) + 900 ribu (Karanganyar/Sukoharjo)',
            'key_regulations' => 'Perda Kota Surakarta tentang pengelolaan lingkungan hidup',
            'government_office' => 'DPMPTSP Kota Surakarta',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Solo',
        ],
        'yogyakarta' => [
            'name' => 'Yogyakarta',
            'province' => 'DI Yogyakarta',
            'slug' => 'yogyakarta',
            'description' => 'Yogyakarta merupakan pusat pendidikan dan kebudayaan dengan industri kreatif, kerajinan, dan teknologi yang berkembang pesat.',
            'industries' => ['kerajinan', 'batik', 'makanan & minuman', 'teknologi', 'kreatif'],
            'industrial_zones' => ['Kawasan Industri Sentolo', 'Kawasan Industri Piyungan', 'Kawasan Industri Sedayu'],
            'population' => '430 ribu (kota) + 3.7 juta (DIY)',
            'key_regulations' => 'Perda DIY tentang pengelolaan lingkungan dan tata ruang',
            'government_office' => 'DPMPTSP DIY',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Yogyakarta',
        ],
        'malang' => [
            'name' => 'Malang',
            'province' => 'Jawa Timur',
            'slug' => 'malang',
            'description' => 'Malang merupakan kota industri dan pendidikan di Jawa Timur dengan sektor agroindustri, makanan olahan, dan rokok yang dominan.',
            'industries' => ['rokok', 'makanan & minuman', 'keramik', 'farmasi', 'agro-industri'],
            'industrial_zones' => ['Kawasan Industri PIER (Pasuruan)', 'Kawasan Industri Ngoro (Mojokerto)', 'Sentra Industri Singosari'],
            'population' => '870 ribu (kota) + 2.6 juta (kabupaten)',
            'key_regulations' => 'Perda Kota/Kabupaten Malang tentang perizinan lingkungan',
            'government_office' => 'DPMPTSP Kota Malang / DPMPTSP Kabupaten Malang',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Malang',
        ],
        'gresik' => [
            'name' => 'Gresik',
            'province' => 'Jawa Timur',
            'slug' => 'gresik',
            'description' => 'Gresik adalah kawasan industri berat di Jawa Timur dengan industri semen (Semen Indonesia), petrokimia, dan galangan kapal.',
            'industries' => ['semen', 'petrokimia', 'galangan kapal', 'manufaktur', 'logistik'],
            'industrial_zones' => ['Kawasan Industri Gresik (KIG)', 'Java Integrated Industrial & Port Estate (JIIPE)', 'Maspion Industrial Estate'],
            'population' => '1.3 juta',
            'key_regulations' => 'Perda Kabupaten Gresik tentang pengelolaan lingkungan dan B3',
            'government_office' => 'DPMPTSP Kabupaten Gresik',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Gresik',
        ],
        'sidoarjo' => [
            'name' => 'Sidoarjo',
            'province' => 'Jawa Timur',
            'slug' => 'sidoarjo',
            'description' => 'Sidoarjo merupakan kabupaten industri di selatan Surabaya dengan sektor UMKM terbesar di Jawa Timur, termasuk sentra industri tas dan sepatu.',
            'industries' => ['manufaktur', 'tas & sepatu', 'makanan & minuman', 'logistik', 'perikanan'],
            'industrial_zones' => ['Kawasan Industri Berbek', 'Kawasan Industri SIER (Surabaya Industrial Estate Rungkut)', 'Sentra Industri Tanggulangin'],
            'population' => '2.2 juta',
            'key_regulations' => 'Perda Kabupaten Sidoarjo tentang pengendalian pencemaran lingkungan',
            'government_office' => 'DPMPTSP Kabupaten Sidoarjo',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Sidoarjo',
        ],
        'pasuruan' => [
            'name' => 'Pasuruan',
            'province' => 'Jawa Timur',
            'slug' => 'pasuruan',
            'description' => 'Pasuruan memiliki kawasan industri besar PIER (Pasuruan Industrial Estate Rembang) yang menampung ratusan perusahaan multinasional.',
            'industries' => ['manufaktur', 'otomotif', 'makanan & minuman', 'kimia', 'elektronik'],
            'industrial_zones' => ['Pasuruan Industrial Estate Rembang (PIER)', 'Kawasan Industri JIEP Pandaan'],
            'population' => '200 ribu (kota) + 1.6 juta (kabupaten)',
            'key_regulations' => 'Perda Kabupaten Pasuruan tentang penataan ruang dan industri',
            'government_office' => 'DPMPTSP Kabupaten Pasuruan',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Pasuruan',
        ],
        'mojokerto' => [
            'name' => 'Mojokerto',
            'province' => 'Jawa Timur',
            'slug' => 'mojokerto',
            'description' => 'Mojokerto berkembang sebagai kawasan industri baru di Jawa Timur dengan Ngoro Industrial Park yang menampung investasi asing.',
            'industries' => ['manufaktur', 'otomotif', 'makanan & minuman', 'plastik', 'logam'],
            'industrial_zones' => ['Ngoro Industrial Park (NIP)', 'Kawasan Industri Jetis'],
            'population' => '130 ribu (kota) + 1.1 juta (kabupaten)',
            'key_regulations' => 'Perda Kabupaten Mojokerto tentang perizinan berusaha',
            'government_office' => 'DPMPTSP Kabupaten Mojokerto',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Mojokerto',
        ],
        'kudus' => [
            'name' => 'Kudus',
            'province' => 'Jawa Tengah',
            'slug' => 'kudus',
            'description' => 'Kudus terkenal sebagai kota kretek dengan industri rokok terbesar di Indonesia (Djarum, Nojorono) dan industri konveksi yang kuat.',
            'industries' => ['rokok', 'konveksi', 'makanan & minuman', 'elektronik', 'perdagangan'],
            'industrial_zones' => ['Kawasan Industri Kudus', 'Sentra Industri Rokok Kudus'],
            'population' => '870 ribu',
            'key_regulations' => 'Perda Kabupaten Kudus tentang pengelolaan limbah industri',
            'government_office' => 'DPMPTSP Kabupaten Kudus',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Kudus',
        ],
        'pekalongan' => [
            'name' => 'Pekalongan',
            'province' => 'Jawa Tengah',
            'slug' => 'pekalongan',
            'description' => 'Pekalongan dikenal sebagai kota batik dunia dengan industri tekstil, batik, dan garmen yang menjadi tulang punggung ekonomi daerah.',
            'industries' => ['batik', 'tekstil', 'garmen', 'perikanan', 'makanan & minuman'],
            'industrial_zones' => ['Sentra Industri Batik Pekalongan', 'Kawasan Industri Kajen'],
            'population' => '300 ribu (kota) + 900 ribu (kabupaten)',
            'key_regulations' => 'Perda Kota Pekalongan tentang pengelolaan lingkungan industri batik',
            'government_office' => 'DPMPTSP Kota Pekalongan',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Pekalongan',
        ],
        'kendal' => [
            'name' => 'Kendal',
            'province' => 'Jawa Tengah',
            'slug' => 'kendal',
            'description' => 'Kendal memiliki Kawasan Industri Kendal (KIK) hasil kerjasama Indonesia-Singapura yang berkembang pesat sebagai hub industri Jawa Tengah.',
            'industries' => ['manufaktur', 'garmen', 'makanan & minuman', 'komponen otomotif', 'logistik'],
            'industrial_zones' => ['Kawasan Industri Kendal (KIK)', 'Kawasan Industri Kaliwungu'],
            'population' => '1 juta',
            'key_regulations' => 'Perda Kabupaten Kendal tentang investasi dan perizinan lingkungan',
            'government_office' => 'DPMPTSP Kabupaten Kendal',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Kendal',
        ],
        'tegal' => [
            'name' => 'Tegal',
            'province' => 'Jawa Tengah',
            'slug' => 'tegal',
            'description' => 'Tegal merupakan pusat industri logam dan mesin di Jawa Tengah dengan sentra industri kecil menengah yang sudah terkenal secara nasional.',
            'industries' => ['logam', 'mesin', 'alat pertanian', 'makanan & minuman', 'perikanan'],
            'industrial_zones' => ['Sentra Industri Logam Adiwerna', 'Kawasan Industri Talang'],
            'population' => '250 ribu (kota) + 1.4 juta (kabupaten)',
            'key_regulations' => 'Perda Kota/Kabupaten Tegal tentang penataan kawasan industri',
            'government_office' => 'DPMPTSP Kota Tegal',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Tegal',
        ],
        'cilacap' => [
            'name' => 'Cilacap',
            'province' => 'Jawa Tengah',
            'slug' => 'cilacap',
            'description' => 'Cilacap memiliki kilang minyak Pertamina terbesar di Jawa dan pelabuhan besar, menjadikannya pusat industri petrokimia dan energi.',
            'industries' => ['petrokimia', 'minyak & gas', 'semen', 'perikanan', 'kehutanan'],
            'industrial_zones' => ['Kawasan Industri Cilacap', 'Kilang Minyak Pertamina Cilacap'],
            'population' => '1.8 juta',
            'key_regulations' => 'Perda Kabupaten Cilacap tentang pengelolaan limbah B3 dan lingkungan',
            'government_office' => 'DPMPTSP Kabupaten Cilacap',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Cilacap',
        ],
        'medan' => [
            'name' => 'Medan',
            'province' => 'Sumatera Utara',
            'slug' => 'medan',
            'description' => 'Medan adalah kota terbesar di luar Jawa dan pusat industri di Sumatera Utara, dengan kawasan industri yang menampung perusahaan kelapa sawit, karet, dan manufaktur.',
            'industries' => ['kelapa sawit', 'karet', 'manufaktur', 'makanan & minuman', 'perdagangan'],
            'industrial_zones' => ['Kawasan Industri Medan (KIM)', 'Kawasan Industri Mabar', 'Kawasan Industri Deli Serdang'],
            'population' => '2.5 juta',
            'key_regulations' => 'Perda Kota Medan tentang pengelolaan lingkungan dan limbah B3',
            'government_office' => 'DPMPTSP Kota Medan',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Medan',
        ],
        'palembang' => [
            'name' => 'Palembang',
            'province' => 'Sumatera Selatan',
            'slug' => 'palembang',
            'description' => 'Palembang merupakan pusat industri di Sumatera Selatan dengan sektor minyak dan gas, pertambangan, serta industri pengolahan yang berkembang.',
            'industries' => ['minyak & gas', 'karet', 'kelapa sawit', 'pupuk', 'manufaktur'],
            'industrial_zones' => ['Kawasan Industri Sukarame', 'Kawasan Ekonomi Khusus Tanjung Api-Api'],
            'population' => '1.7 juta',
            'key_regulations' => 'Perda Kota Palembang tentang pengelolaan lingkungan hidup',
            'government_office' => 'DPMPTSP Kota Palembang',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Palembang',
        ],
        'batam' => [
            'name' => 'Batam',
            'province' => 'Kepulauan Riau',
            'slug' => 'batam',
            'description' => 'Batam adalah zona perdagangan bebas (FTZ) terbesar di Indonesia dengan ribuan perusahaan manufaktur multinasional, terutama elektronik dan galangan kapal.',
            'industries' => ['elektronik', 'galangan kapal', 'minyak & gas offshore', 'manufaktur', 'logistik'],
            'industrial_zones' => ['Batamindo Industrial Park', 'Kabil Industrial Estate', 'Panbil Industrial Estate', 'Cammo Industrial Park'],
            'population' => '1.2 juta',
            'key_regulations' => 'Peraturan BP Batam dan Perda Kota Batam tentang FTZ dan lingkungan',
            'government_office' => 'BP Batam / DPMPTSP Kota Batam',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Batam',
        ],
        'lampung' => [
            'name' => 'Bandar Lampung',
            'province' => 'Lampung',
            'slug' => 'lampung',
            'description' => 'Lampung merupakan gerbang Sumatera dengan industri agro yang kuat terutama gula, kopi, lada, serta industri pengolahan hasil pertanian.',
            'industries' => ['agro-industri', 'gula', 'kopi', 'lada', 'manufaktur'],
            'industrial_zones' => ['Kawasan Industri Lampung', 'Kawasan Industri Way Halim'],
            'population' => '1 juta (kota) + 9 juta (provinsi)',
            'key_regulations' => 'Perda Provinsi Lampung tentang pengelolaan lingkungan dan agroindustri',
            'government_office' => 'DPMPTSP Kota Bandar Lampung',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Lampung',
        ],
        'pekanbaru' => [
            'name' => 'Pekanbaru',
            'province' => 'Riau',
            'slug' => 'pekanbaru',
            'description' => 'Pekanbaru merupakan pusat ekonomi Riau dengan industri minyak dan gas (Chevron, Pertamina) serta kelapa sawit yang mendominasi perekonomian.',
            'industries' => ['minyak & gas', 'kelapa sawit', 'kertas & pulp', 'karet', 'perdagangan'],
            'industrial_zones' => ['Kawasan Industri Tenayan', 'Kawasan Ekonomi Khusus Dumai'],
            'population' => '1.1 juta',
            'key_regulations' => 'Perda Kota Pekanbaru tentang pengendalian pencemaran dan limbah B3',
            'government_office' => 'DPMPTSP Kota Pekanbaru',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Pekanbaru',
        ],
        'padang' => [
            'name' => 'Padang',
            'province' => 'Sumatera Barat',
            'slug' => 'padang',
            'description' => 'Padang sebagai ibukota Sumatera Barat memiliki industri semen (Semen Padang), pertambangan, dan pengolahan hasil laut yang berkembang.',
            'industries' => ['semen', 'pertambangan', 'perikanan', 'makanan & minuman', 'pariwisata'],
            'industrial_zones' => ['Kawasan Industri Padang (Indarung)', 'Pelabuhan Teluk Bayur Industrial Area'],
            'population' => '940 ribu',
            'key_regulations' => 'Perda Kota Padang tentang pengelolaan lingkungan hidup',
            'government_office' => 'DPMPTSP Kota Padang',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Padang',
        ],
        'jambi' => [
            'name' => 'Jambi',
            'province' => 'Jambi',
            'slug' => 'jambi',
            'description' => 'Jambi memiliki potensi industri kelapa sawit, karet, dan pertambangan batubara yang besar, serta industri pengolahan turunannya.',
            'industries' => ['kelapa sawit', 'karet', 'batubara', 'minyak & gas', 'kehutanan'],
            'industrial_zones' => ['Kawasan Industri Muaro Jambi', 'Kawasan Industri Tanjung Jabung'],
            'population' => '600 ribu (kota) + 3.5 juta (provinsi)',
            'key_regulations' => 'Perda Provinsi Jambi tentang pengelolaan lingkungan dan AMDAL',
            'government_office' => 'DPMPTSP Kota Jambi',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Jambi',
        ],
        'pangkalpinang' => [
            'name' => 'Pangkal Pinang',
            'province' => 'Bangka Belitung',
            'slug' => 'pangkalpinang',
            'description' => 'Pangkal Pinang dan Bangka Belitung terkenal dengan industri pertambangan timah serta pengolahan hasil tambang yang memerlukan izin lingkungan ketat.',
            'industries' => ['pertambangan timah', 'pengolahan timah', 'perikanan', 'kelapa sawit', 'pariwisata'],
            'industrial_zones' => ['Kawasan Industri Timah Muntok', 'Kawasan Pertambangan Bangka'],
            'population' => '210 ribu (kota) + 1.5 juta (provinsi)',
            'key_regulations' => 'Perda Provinsi Babel tentang pertambangan berkelanjutan dan AMDAL',
            'government_office' => 'DPMPTSP Kota Pangkal Pinang',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Pangkal Pinang',
        ],
        'balikpapan' => [
            'name' => 'Balikpapan',
            'province' => 'Kalimantan Timur',
            'slug' => 'balikpapan',
            'description' => 'Balikpapan adalah pusat industri minyak dan gas di Kalimantan Timur dengan kilang Pertamina dan berbagai perusahaan oil & gas multinasional.',
            'industries' => ['minyak & gas', 'petrokimia', 'logistik', 'konstruksi', 'jasa pertambangan'],
            'industrial_zones' => ['Kariangau Industrial Estate', 'Kawasan Industri Balikpapan (KIPB)'],
            'population' => '700 ribu',
            'key_regulations' => 'Perda Kota Balikpapan tentang pengelolaan lingkungan dan limbah B3',
            'government_office' => 'DPMPTSP Kota Balikpapan',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Balikpapan',
        ],
        'samarinda' => [
            'name' => 'Samarinda',
            'province' => 'Kalimantan Timur',
            'slug' => 'samarinda',
            'description' => 'Samarinda sebagai ibukota Kaltim merupakan pusat industri batubara dan kehutanan dengan berbagai perusahaan tambang besar.',
            'industries' => ['batubara', 'kehutanan', 'kelapa sawit', 'konstruksi', 'perdagangan'],
            'industrial_zones' => ['Kawasan Industri Samarinda', 'Kawasan Pertambangan Kutai Kartanegara'],
            'population' => '870 ribu',
            'key_regulations' => 'Perda Kota Samarinda tentang pengendalian pencemaran lingkungan',
            'government_office' => 'DPMPTSP Kota Samarinda',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Samarinda',
        ],
        'banjarmasin' => [
            'name' => 'Banjarmasin',
            'province' => 'Kalimantan Selatan',
            'slug' => 'banjarmasin',
            'description' => 'Banjarmasin merupakan pusat perdagangan dan industri di Kalimantan Selatan dengan sektor pertambangan, kehutanan, dan karet yang kuat.',
            'industries' => ['pertambangan', 'karet', 'kelapa sawit', 'kayu', 'perikanan'],
            'industrial_zones' => ['Kawasan Industri Banjarmasin', 'Kawasan Industri Bati-Bati Tanah Laut'],
            'population' => '700 ribu',
            'key_regulations' => 'Perda Kota Banjarmasin tentang pengelolaan lingkungan dan limbah',
            'government_office' => 'DPMPTSP Kota Banjarmasin',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Banjarmasin',
        ],
        'pontianak' => [
            'name' => 'Pontianak',
            'province' => 'Kalimantan Barat',
            'slug' => 'pontianak',
            'description' => 'Pontianak merupakan ibukota Kalimantan Barat dengan industri pengolahan karet, kayu, kelapa sawit, dan perdagangan lintas batas.',
            'industries' => ['karet', 'kayu', 'kelapa sawit', 'perikanan', 'perdagangan'],
            'industrial_zones' => ['Kawasan Industri Pontianak', 'Kawasan Industri Kubu Raya'],
            'population' => '650 ribu',
            'key_regulations' => 'Perda Kota Pontianak tentang pengelolaan lingkungan hidup',
            'government_office' => 'DPMPTSP Kota Pontianak',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Pontianak',
        ],
        'bontang' => [
            'name' => 'Bontang',
            'province' => 'Kalimantan Timur',
            'slug' => 'bontang',
            'description' => 'Bontang adalah kota industri LNG dan pupuk terbesar di Indonesia dengan Badak NGL dan Pupuk Kaltim sebagai industri utama.',
            'industries' => ['LNG', 'pupuk', 'petrokimia', 'minyak & gas', 'logistik'],
            'industrial_zones' => ['Kawasan Industri Bontang (Badak LNG)', 'Kawasan Pupuk Kaltim'],
            'population' => '180 ribu',
            'key_regulations' => 'Perda Kota Bontang tentang pengelolaan lingkungan dan AMDAL industri',
            'government_office' => 'DPMPTSP Kota Bontang',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Bontang',
        ],
        'makassar' => [
            'name' => 'Makassar',
            'province' => 'Sulawesi Selatan',
            'slug' => 'makassar',
            'description' => 'Makassar adalah pusat ekonomi Indonesia Timur dengan pelabuhan besar, kawasan industri, dan menjadi hub perdagangan Sulawesi.',
            'industries' => ['manufaktur', 'perikanan', 'perdagangan', 'konstruksi', 'logistik'],
            'industrial_zones' => ['Kawasan Industri Makassar (KIMA)', 'Kawasan Ekonomi Khusus (KEK) Bitung'],
            'population' => '1.5 juta',
            'key_regulations' => 'Perda Kota Makassar tentang pengelolaan lingkungan dan tata ruang',
            'government_office' => 'DPMPTSP Kota Makassar',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Makassar',
        ],
        'manado' => [
            'name' => 'Manado',
            'province' => 'Sulawesi Utara',
            'slug' => 'manado',
            'description' => 'Manado merupakan pusat ekonomi di Sulawesi Utara dengan industri perikanan, kopra, dan pariwisata yang berkembang.',
            'industries' => ['perikanan', 'kopra', 'pariwisata', 'perdagangan', 'konstruksi'],
            'industrial_zones' => ['Kawasan Ekonomi Khusus Bitung', 'Kawasan Industri Manado'],
            'population' => '450 ribu',
            'key_regulations' => 'Perda Kota Manado tentang pengelolaan lingkungan pesisir',
            'government_office' => 'DPMPTSP Kota Manado',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Manado',
        ],
        'morowali' => [
            'name' => 'Morowali',
            'province' => 'Sulawesi Tengah',
            'slug' => 'morowali',
            'description' => 'Morowali adalah pusat smelter nikel terbesar di Indonesia dengan Indonesia Morowali Industrial Park (IMIP) yang dioperasikan oleh perusahaan multinasional.',
            'industries' => ['nikel smelter', 'pertambangan', 'stainless steel', 'logistik', 'energi'],
            'industrial_zones' => ['Indonesia Morowali Industrial Park (IMIP)', 'Indonesia Weda Bay Industrial Park'],
            'population' => '120 ribu',
            'key_regulations' => 'Perda Kabupaten Morowali tentang AMDAL pertambangan dan smelter',
            'government_office' => 'DPMPTSP Kabupaten Morowali',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Morowali',
        ],
        'denpasar' => [
            'name' => 'Denpasar & Bali',
            'province' => 'Bali',
            'slug' => 'denpasar',
            'description' => 'Bali memiliki regulasi lingkungan yang ketat untuk melindungi pariwisata, dengan industri kreatif, kerajinan, dan pengolahan makanan yang memerlukan izin khusus.',
            'industries' => ['pariwisata', 'kerajinan', 'makanan & minuman', 'kreatif', 'tekstil'],
            'industrial_zones' => ['Kawasan Industri Pengambengan', 'Sentra Kerajinan Gianyar', 'Kawasan Industri Tabanan'],
            'population' => '960 ribu (kota) + 4.3 juta (provinsi)',
            'key_regulations' => 'Perda Provinsi Bali tentang pengelolaan lingkungan dan pariwisata berkelanjutan',
            'government_office' => 'DPMPTSP Kota Denpasar / DPMPTSP Provinsi Bali',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Bali',
        ],
        'bintan' => [
            'name' => 'Bintan',
            'province' => 'Kepulauan Riau',
            'slug' => 'bintan',
            'description' => 'Bintan memiliki kawasan industri dan free trade zone yang menarik investasi asing terutama dari Singapura dan Malaysia.',
            'industries' => ['manufaktur', 'elektronik', 'galangan kapal', 'pariwisata', 'agro-industri'],
            'industrial_zones' => ['Bintan Industrial Estate', 'Lobam Industrial Estate', 'Galang Batang Industrial Zone'],
            'population' => '170 ribu',
            'key_regulations' => 'Perda Kabupaten Bintan dan FTZ tentang perizinan lingkungan',
            'government_office' => 'DPMPTSP Kabupaten Bintan',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Bintan',
        ],
        'dumai' => [
            'name' => 'Dumai',
            'province' => 'Riau',
            'slug' => 'dumai',
            'description' => 'Dumai merupakan kota pelabuhan dan Kawasan Ekonomi Khusus di Riau dengan industri pengolahan minyak, kelapa sawit, dan ekspor komoditas.',
            'industries' => ['minyak & gas', 'kelapa sawit', 'petrokimia', 'logistik', 'ekspor'],
            'industrial_zones' => ['Kawasan Ekonomi Khusus Dumai', 'Pelabuhan Dumai Industrial Area'],
            'population' => '300 ribu',
            'key_regulations' => 'Perda Kota Dumai dan KEK tentang pengelolaan lingkungan industri',
            'government_office' => 'DPMPTSP Kota Dumai',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Dumai',
        ],
        'sorong' => [
            'name' => 'Sorong',
            'province' => 'Papua Barat Daya',
            'slug' => 'sorong',
            'description' => 'Sorong adalah kota industri migas dan perikanan di Papua Barat Daya dengan potensi pertambangan dan KEK yang berkembang.',
            'industries' => ['minyak & gas', 'perikanan', 'pertambangan', 'kehutanan', 'logistik'],
            'industrial_zones' => ['Kawasan Ekonomi Khusus Sorong', 'Kawasan Industri Perikanan Sorong'],
            'population' => '250 ribu',
            'key_regulations' => 'Perda Kota Sorong tentang pengelolaan lingkungan dan AMDAL',
            'government_office' => 'DPMPTSP Kota Sorong',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Sorong',
        ],
        'magelang' => [
            'name' => 'Magelang',
            'province' => 'Jawa Tengah',
            'slug' => 'magelang',
            'description' => 'Magelang memiliki industri makanan, minuman, serta kerajinan yang berkembang, didukung oleh posisi strategis antara Yogyakarta dan Semarang.',
            'industries' => ['makanan & minuman', 'kerajinan', 'tekstil', 'pertambangan galian C', 'agro-industri'],
            'industrial_zones' => ['Kawasan Industri Mungkid', 'Sentra Industri Kerajinan Magelang'],
            'population' => '130 ribu (kota) + 1.3 juta (kabupaten)',
            'key_regulations' => 'Perda Kabupaten Magelang tentang penataan ruang dan perizinan',
            'government_office' => 'DPMPTSP Kota Magelang / DPMPTSP Kabupaten Magelang',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Magelang',
        ],
        'demak' => [
            'name' => 'Demak',
            'province' => 'Jawa Tengah',
            'slug' => 'demak',
            'description' => 'Demak berkembang sebagai kawasan industri satelit Semarang dengan industri garmen, makanan, dan manufaktur ringan.',
            'industries' => ['garmen', 'makanan & minuman', 'mebel', 'manufaktur ringan', 'perikanan'],
            'industrial_zones' => ['Kawasan Industri Sayung', 'Kawasan Industri Karangawen'],
            'population' => '1.2 juta',
            'key_regulations' => 'Perda Kabupaten Demak tentang pengelolaan lingkungan pesisir dan industri',
            'government_office' => 'DPMPTSP Kabupaten Demak',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di Demak',
        ],
        'nusantara' => [
            'name' => 'IKN Nusantara',
            'province' => 'Kalimantan Timur',
            'slug' => 'nusantara',
            'description' => 'Ibu Kota Nusantara (IKN) merupakan proyek ibu kota baru Indonesia di Kalimantan Timur dengan pembangunan infrastruktur masif yang memerlukan izin lingkungan dan AMDAL berskala besar.',
            'industries' => ['konstruksi', 'infrastruktur', 'teknologi', 'energi terbarukan', 'logistik'],
            'industrial_zones' => ['Kawasan Inti Pusat Pemerintahan IKN', 'Kawasan Ekonomi IKN', 'Kawasan Industri Penajam Paser Utara'],
            'population' => 'Dalam pembangunan (target 1.9 juta)',
            'key_regulations' => 'UU IKN No. 3/2022 dan Perpres tentang AMDAL kawasan strategis nasional',
            'government_office' => 'Otorita IKN / DPMPTSP Kab. Penajam Paser Utara',
            'whatsapp_text' => 'Halo Bizmark, saya butuh konsultasi perizinan di IKN Nusantara',
        ],
    ],

    // Services eligible for location pages (subset of services_data)
    'services' => [
        'perizinan-lb3', 'amdal', 'ukl-upl', 'oss-nib', 'pbg-slf',
        'izin-operasional', 'konsultan-lingkungan', 'monitoring-digital', 'izin-k3',
    ],

    // Current year for dynamic content
    'current_year' => 2026,

    // Cache duration in minutes
    'cache_ttl' => 1440, // 24 hours
];
