<?php

return [
    // Shared secret for validating webhook payload signature (HMAC SHA-256).
    'secret' => env('EMAIL_WEBHOOK_SECRET', ''),

    // Default recipient used when the webhook payload omits the original mailbox.
    'default_recipient' => env('EMAIL_WEBHOOK_DEFAULT_RECIPIENT', 'info@bizmark.id'),

    // Header containing signature generated by the inbound email worker.
    'signature_header' => env('EMAIL_WEBHOOK_SIGNATURE_HEADER', 'X-Webhook-Signature'),

    // Enable after EMAIL_WEBHOOK_SECRET is configured end-to-end.
    'require_signature' => (bool) env('EMAIL_WEBHOOK_REQUIRE_SIGNATURE', false),

    // Optional IP allowlist for the webhook sender. Comma-separated in .env.
    'allowed_ips' => array_filter(array_map(
        'trim',
        explode(',', (string) env('EMAIL_WEBHOOK_ALLOWED_IPS', ''))
    )),
];
