<?php

return [
    'perizinan-lb3' => [
        'title' => 'Jasa Konsultan Izin Limbah B3 Profesional & Terjangkau',
        'slug' => 'perizinan-lb3',
        'short_description' => 'Solusi lengkap perizinan Limbah B3 — dari TPS, pengumpulan, pengolahan, pemanfaatan, hingga penimbunan. Konsultan berpengalaman mendampingi & mewakili perusahaan Anda dalam seluruh proses.',
        'long_description' => 'Bizmark.id adalah mitra konsultan profesional yang mendampingi dan mewakili perusahaan Anda dalam seluruh proses pengurusan izin Limbah Bahan Berbahaya dan Beracun (B3). Dari izin TPS, pengumpulan, pengangkutan, pengolahan berdasarkan teknologi (insinerasi, stabilisasi, fisika-kimia), pemanfaatan (FABA, recovery oli bekas), hingga penimbunan dan dumping — kami menangani semua jenis perizinan limbah B3 sesuai PP No. 22 Tahun 2021 dan Permen LHK No. 6 Tahun 2021. Dengan pengalaman >10 tahun dan biaya konsultasi yang terjangkau, kami memastikan proses perizinan Anda cepat, transparan, dan patuh regulasi.',
        'icon' => 'fa-biohazard',
        'color' => '#DC2626',
        'meta_keywords' => 'jasa konsultan izin limbah b3, perizinan limbah b3, izin limbah b3 murah, konsultan limbah b3 profesional, izin tps limbah b3, izin pengolahan limbah b3, izin pengumpulan limbah b3, pengelolaan limbah b3, biaya izin limbah b3, rintek penyimpanan limbah b3',
        'category' => 'LINGKUNGAN',
        'price_range' => 'Mulai Rp 25 Jt',
        'process_time' => '30-240 Hari',
        'key_features' => [
            'Penyusunan dokumen teknis TPS, pengumpulan, pengolahan & pemanfaatan limbah B3',
            'Koordinasi dengan DLHK kabupaten/kota dan provinsi',
            'Pendampingan inspeksi/verifikasi lapangan oleh petugas pengawas',
            'Pengurusan manifest limbah B3 dan sistem pelaporan online',
            'Pemetaan regulasi terbaru PP No. 22/2021 dan PermenLHK terkait',
            'Dukungan pasca-izin: pelaporan berkala & audit kepatuhan',
        ],
        'documents_required' => [
            'NIB / Izin Usaha yang masih berlaku',
            'Dokumen lingkungan (AMDAL atau UKL-UPL) yang telah disetujui',
            'Neraca limbah B3 (jenis, volume, sumber)',
            'Denah lokasi & layout TPS Limbah B3',
            'Desain teknis fasilitas pengelolaan (gambar & spesifikasi)',
            'SOP Pengelolaan & Tanggap Darurat Limbah B3',
            'Sertifikat tenaga ahli pengelola limbah B3',
            'Kontrak kerjasama dengan mitra pengolah/pemanfaat berizin',
        ],
        'process_steps_detail' => [
            ['title' => 'Asesmen & Identifikasi Limbah', 'desc' => 'Identifikasi jenis, karakteristik, volume limbah B3 dan kebutuhan perizinan spesifik.'],
            ['title' => 'Penyusunan Dokumen Teknis', 'desc' => 'Menyiapkan desain TPS, SOP, neraca limbah, dan seluruh dokumen persyaratan.'],
            ['title' => 'Pengajuan ke DLHK', 'desc' => 'Submit permohonan izin secara daring melalui sistem OSS dan koordinasi administratif.'],
            ['title' => 'Verifikasi & Inspeksi Lapangan', 'desc' => 'Pendampingan tim Anda saat inspeksi lapangan oleh petugas dari DLHK.'],
            ['title' => 'Penerbitan Izin', 'desc' => 'Izin terbit setelah lolos verifikasi — kami bantu arsip dan pelaporan berkala.'],
        ],
        'sub_services' => [
            'tps-limbah-b3' => [
                'title' => 'TPS Limbah B3 (Penyimpanan Sementara)',
                'short_description' => 'Izin untuk fasilitas penyimpanan sementara limbah B3 di area perusahaan sesuai standar teknis yang berlaku.',
                'long_description' => 'Tempat Penyimpanan Sementara (TPS) Limbah B3 adalah fasilitas wajib bagi setiap perusahaan penghasil limbah B3 sebelum limbah diserahkan ke pihak pengolah/pemanfaat berizin. Sesuai PP No. 22 Tahun 2021, TPS Limbah B3 harus memenuhi persyaratan teknis: atap tertutup, lantai kedap air, sistem drainase tertutup, ventilasi memadai, dan area tanggap darurat. Kami membantu penyiapan desain teknis TPS, dokumen permohonan izin, koordinasi dengan DLHK, hingga pendampingan verifikasi lapangan.',
                'icon' => 'fa-warehouse',
                'meta_keywords' => 'tps limbah b3, penyimpanan sementara limbah b3, izin tps b3, gudang limbah b3',
                'process_steps' => ['Asesmen lokasi & kebutuhan TPS', 'Penyusunan desain teknis TPS', 'Penyiapan dokumen permohonan', 'Pengajuan ke DLHK', 'Verifikasi lapangan', 'Penerbitan izin TPS'],
                'requirements' => ['NIB & izin usaha aktif', 'Neraca limbah B3', 'Denah lokasi TPS', 'Desain teknis TPS sesuai standar', 'Dokumen pengelolaan lingkungan (UKL-UPL/AMDAL)'],
                'duration' => '30-60 Hari',
            ],
            'pengumpulan-limbah-b3' => [
                'title' => 'Izin Pengumpulan Limbah B3',
                'short_description' => 'Izin bagi pihak yang mengumpulkan limbah B3 dari berbagai sumber penghasil untuk disalurkan ke pengolah berizin.',
                'long_description' => 'Kegiatan pengumpulan limbah B3 adalah proses mengumpulkan limbah B3 dari berbagai penghasil untuk kemudian diserahkan ke penyimpan, pemanfaat, pengolah, atau penimbun berizin. Izin pengumpulan diperlukan oleh pihak ketiga yang menjalankan bisnis pengumpulan limbah B3. Persyaratan mencakup fasilitas penyimpanan yang memadai, tenaga ahli K3 dan lingkungan, serta SOP penanganan darurat. Kami mendampingi mulai dari feasibility study, penyusunan dokumen teknis, hingga perolehan izin dari KLHK atau DLHK provinsi/kabupaten.',
                'icon' => 'fa-people-carry',
                'meta_keywords' => 'izin pengumpulan limbah b3, pengumpul limbah b3, jasa pengumpulan b3',
                'process_steps' => ['Feasibility study', 'Penyusunan dokumen teknis', 'Persiapan fasilitas pengumpulan', 'Pengajuan permohonan izin', 'Verifikasi teknis lapangan', 'Penerbitan izin pengumpulan'],
                'requirements' => ['Akta pendirian perusahaan', 'NIB & izin usaha', 'Dokumen lingkungan', 'Tenaga ahli K3 & lingkungan bersertifikat', 'SOP penanganan darurat tumpahan B3'],
                'duration' => '60-90 Hari',
            ],
            'pengangkutan-limbah-b3' => [
                'title' => 'Izin Pengangkutan Limbah B3',
                'short_description' => 'Izin pengangkutan limbah B3 menggunakan sarana angkut sesuai standar keselamatan dan regulasi yang berlaku.',
                'long_description' => 'Pengangkutan limbah B3 wajib menggunakan kendaraan yang memenuhi persyaratan teknis khusus dan dilengkapi dengan dokumen pengangkutan (manifest). Izin pengangkutan diterbitkan oleh Kementerian Perhubungan setelah mendapat rekomendasi dari KLHK. Persyaratan meliputi kendaraan dengan spesifikasi khusus, pengemudi bersertifikat, asuransi pengangkutan B3, dan rencana tanggap darurat di perjalanan.',
                'icon' => 'fa-truck',
                'meta_keywords' => 'izin angkut limbah b3, pengangkutan limbah b3, transporter b3, manifest limbah b3',
                'process_steps' => ['Audit kendaraan pengangkut', 'Penyusunan SOP pengangkutan', 'Pengajuan rekomendasi KLHK', 'Pengajuan izin ke Kemenhub', 'Sertifikasi pengemudi', 'Penerbitan izin angkut'],
                'requirements' => ['Kendaraan sesuai spesifikasi B3', 'Sertifikat pengemudi B3', 'Asuransi pengangkutan B3', 'SOP tanggap darurat', 'Rekomendasi dari KLHK'],
                'duration' => '45-90 Hari',
            ],
            'pengolahan-limbah-b3' => [
                'title' => 'Izin Pengolahan Limbah B3',
                'short_description' => 'Izin untuk fasilitas pengolahan limbah B3 dengan berbagai teknologi (insinerasi, stabilisasi, dll).',
                'long_description' => 'Pengolahan limbah B3 bertujuan mengurangi atau menghilangkan sifat bahaya dan beracun dari limbah sebelum dibuang ke lingkungan. Teknologi pengolahan meliputi insinerasi (pembakaran suhu tinggi), stabilisasi/solidifikasi, pengolahan fisika-kimia, dan pengolahan biologis. Izin pengolahan diterbitkan oleh KLHK atau pemerintah daerah sesuai skala dan jenis teknologi. Persyaratan sangat ketat mencakup kajian kelayakan teknis, AMDAL, uji coba operasi, dan monitoring emisi/efluen.',
                'icon' => 'fa-recycle',
                'meta_keywords' => 'izin pengolahan limbah b3, insinerasi limbah b3, pengolah limbah b3, teknologi pengolahan b3',
                'process_steps' => ['Kajian kelayakan teknis', 'Penyusunan AMDAL/UKL-UPL', 'Desain fasilitas pengolahan', 'Pengajuan izin ke KLHK', 'Uji coba operasi (commissioning)', 'Monitoring & evaluasi operasional'],
                'requirements' => ['Studi kelayakan teknis & ekonomi', 'Dokumen AMDAL', 'Desain engineering fasilitas', 'Tenaga ahli pengolahan limbah', 'Sistem monitoring emisi/efluen'],
                'duration' => '90-180 Hari',
            ],
            'pemanfaatan-limbah-b3' => [
                'title' => 'Izin Pemanfaatan Limbah B3',
                'short_description' => 'Izin pemanfaatan limbah B3 sebagai bahan baku substitusi atau sumber energi alternatif secara aman.',
                'long_description' => 'Pemanfaatan limbah B3 adalah kegiatan menggunakan kembali (reuse), daur ulang (recycle), atau perolehan kembali (recovery) limbah B3 untuk dijadikan bahan baku atau sumber energi. Contoh: fly ash & bottom ash (FABA) untuk bahan bangunan, used oil untuk bahan bakar alternatif, atau used battery untuk recovery logam. Izin pemanfaatan mensyaratkan bukti bahwa proses pemanfaatan tidak menimbulkan dampak negatif terhadap lingkungan dan kesehatan.',
                'icon' => 'fa-sync-alt',
                'meta_keywords' => 'izin pemanfaatan limbah b3, daur ulang limbah b3, recovery limbah b3, faba limbah b3',
                'process_steps' => ['Identifikasi jenis limbah & potensi pemanfaatan', 'Uji laboratorium karakteristik limbah', 'Penyusunan dokumen teknis pemanfaatan', 'Pengajuan izin ke KLHK/DLHK', 'Uji coba pemanfaatan', 'Monitoring kualitas produk hasil pemanfaatan'],
                'requirements' => ['Hasil uji laboratorium limbah', 'Dokumen teknis proses pemanfaatan', 'Bukti pasar/pengguna produk hasil', 'Dokumen lingkungan (AMDAL/UKL-UPL)', 'SOP pengendalian mutu'],
                'duration' => '60-120 Hari',
            ],
            'penimbunan-limbah-b3' => [
                'title' => 'Izin Penimbunan Limbah B3',
                'short_description' => 'Izin untuk fasilitas penimbunan akhir limbah B3 yang telah diolah (landfill khusus B3).',
                'long_description' => 'Penimbunan limbah B3 adalah metode pembuangan akhir limbah B3 yang telah distabilisasi/disolidifikasi ke dalam fasilitas landfill khusus. Fasilitas penimbunan harus dilengkapi lapisan kedap (liner), sistem pengumpul lindi, monitoring air tanah, dan rencana penutupan pasca-operasi. Izin penimbunan merupakan izin paling ketat karena risiko kontaminasi jangka panjang terhadap tanah dan air tanah.',
                'icon' => 'fa-mountain',
                'meta_keywords' => 'izin penimbunan limbah b3, landfill b3, disposal limbah b3, penimbunan akhir b3',
                'process_steps' => ['Studi hidrogeologi lokasi', 'Desain fasilitas penimbunan', 'Penyusunan AMDAL', 'Pengajuan izin ke KLHK', 'Konstruksi fasilitas', 'Monitoring air tanah berkala'],
                'requirements' => ['Studi kelayakan lokasi', 'Studi hidrogeologi', 'AMDAL lengkap', 'Desain engineering landfill', 'Rencana penutupan & pasca-penutupan'],
                'duration' => '120-240 Hari',
            ],
        ],
        'faq' => [
            ['q' => 'Berapa biaya jasa konsultan izin limbah B3?', 'a' => 'Biaya jasa konsultan izin limbah B3 mulai Rp 7 juta untuk izin TPS hingga Rp 150 juta untuk izin penimbunan. Kami menawarkan harga terjangkau dengan konsultasi awal gratis. Hubungi kami untuk penawaran khusus sesuai kebutuhan perusahaan Anda.'],
            ['q' => 'Apa saja jenis perizinan limbah B3?', 'a' => 'Perizinan limbah B3 meliputi izin TPS (Penyimpanan Sementara), pengumpulan, pengangkutan, pengolahan, pemanfaatan, penimbunan, dan dumping (pembuangan ke laut). Jenis izin yang dibutuhkan tergantung pada kegiatan pengelolaan limbah B3 yang dilakukan perusahaan Anda.'],
            ['q' => 'Berapa lama proses pengurusan izin limbah B3?', 'a' => 'Waktu pengurusan bervariasi: izin TPS 30-60 hari, izin pengumpulan 60-90 hari, izin pengolahan 90-180 hari, izin penimbunan 120-240 hari. Faktor yang mempengaruhi meliputi kelengkapan dokumen, respons instansi, dan kompleksitas teknis.'],
            ['q' => 'Apa itu Rintek (Rincian Teknis) dan mengapa penting?', 'a' => 'Rintek adalah dokumen rincian teknis fasilitas penyimpanan/pengolahan limbah B3 yang menjadi lampiran wajib dalam pengajuan PERTEK LB3. Rintek digunakan DLHK sebagai acuan verifikasi lapangan dan harus konsisten dengan dokumen AMDAL/UKL-UPL perusahaan.'],
            ['q' => 'Apa perbedaan persyaratan izin pengolahan berdasarkan teknologi?', 'a' => 'Persyaratan berbeda per teknologi: insinerasi memerlukan AMDAL + sistem pengendalian emisi, stabilisasi/solidifikasi memerlukan uji TCLP, pengolahan fisika-kimia memerlukan desain IPAL + PERTEK efluen, pengolahan biologis memerlukan uji biodegradabilitas.'],
            ['q' => 'Apakah Bizmark.id bisa mewakili perusahaan dalam pengurusan izin?', 'a' => 'Ya. Kami bertindak sebagai pihak ketiga yang mendampingi dan/atau mewakili perusahaan dalam seluruh proses — mulai pengajuan dokumen, koordinasi dengan DLHK/KLHK, pendampingan inspeksi lapangan, hingga pelaporan berkala pasca-izin.'],
            ['q' => 'Apa sanksi jika tidak memiliki izin limbah B3?', 'a' => 'Sanksi pelanggaran pengelolaan limbah B3 sangat berat: denda administratif hingga Rp 5 miliar, pencabutan izin usaha, tanggung jawab perdata, hingga pidana penjara maksimal 15 tahun sesuai UU No. 32/2009 tentang PPLH.'],
            ['q' => 'Dokumen apa saja yang diperlukan untuk mengurus izin limbah B3?', 'a' => 'Dokumen umum meliputi: NIB/izin usaha, dokumen lingkungan (AMDAL/UKL-UPL), neraca limbah B3, denah lokasi, desain teknis fasilitas, SOP pengelolaan, dan tenaga ahli bersertifikat. Persyaratan spesifik berbeda untuk setiap jenis izin.'],
        ],
    ],
    'amdal' => [
        'title' => 'Jasa Pengurusan AMDAL — Tenaga Ahli Bersertifikat, Standar Teknis Terjamin',
        'slug' => 'amdal',
        'short_description' => 'Jasa pengurusan AMDAL oleh tenaga ahli bersertifikat KTPA dengan metodologi analisis terstandar. Pengurangan risiko penolakan hingga 95% — dari penyusunan KA-ANDAL, studi ANDAL, RKL-RPL, hingga persetujuan lingkungan terbit. Konsultasi gratis dengan ahli.',
        'long_description' => 'Bizmark.ID menyediakan jasa pengurusan AMDAL (Analisis Mengenai Dampak Lingkungan) secara end-to-end dengan standar teknis terjamin dan metodologi analisis yang mengacu pada best practice internasional. Tim penyusun kami terdiri dari tenaga ahli bersertifikat KTPA dengan keahlian lintas disiplin—fisika-kimia, biologi, sosial-ekonomi, dan K3—yang berpengalaman menangani 50+ proyek AMDAL di berbagai sektor. Pendekatan sistematis kami terbukti mengurangi risiko penolakan dokumen di Komisi Penilai AMDAL, dengan tingkat keberhasilan 95%. Layanan mencakup penapisan, penyusunan KA-ANDAL, studi ANDAL, RKL-RPL, koordinasi dengan Komisi Penilai AMDAL pusat/daerah, konsultasi publik, hingga terbitnya persetujuan lingkungan sesuai PP No. 22 Tahun 2021 dan Permen LHK No. 4 Tahun 2021. Mulai dari Rp 80 juta, konsultasi langsung dengan tenaga ahli kami gratis.',
        'icon' => 'fa-leaf',
        'color' => '#059669',
        'meta_keywords' => 'jasa pengurusan amdal, jasa amdal, konsultan amdal, biaya amdal, pengurusan amdal, penyusunan amdal, jasa konsultan amdal, amdal karawang, amdal jakarta, dokumen amdal, tenaga ahli amdal bersertifikat, standar teknis amdal, metodologi analisis amdal, risiko penolakan amdal, amdal manufaktur, amdal pertambangan, ka-andal, rkl-rpl',
        'category' => 'LINGKUNGAN',
        'price_range' => 'Mulai Rp 150 Jt',
        'process_time' => '6-12 Bulan',
        'key_features' => [
            'Penyusunan KA-ANDAL, ANDAL, dan RKL-RPL oleh tim bersertifikat',
            'Pelibatan masyarakat & konsultasi publik sesuai regulasi',
            'Koordinasi dengan Komisi Penilai AMDAL pusat/daerah',
            'Studi baseline lingkungan (fisik-kimia, biologi, sosial-ekonomi)',
            'Pendampingan sidang komisi hingga persetujuan lingkungan terbit',
            'Monitoring implementasi RKL-RPL pasca-persetujuan',
        ],
        'documents_required' => [
            'Profil perusahaan & akta pendirian',
            'NIB dan izin lokasi/kesesuaian tata ruang',
            'Rencana detail kegiatan (DED/feasibility study)',
            'Peta lokasi & tata ruang wilayah',
            'Data baseline lingkungan (jika sudah ada)',
            'NPWP perusahaan dan KTP direktur',
            'Bukti status kepemilikan/penguasaan lahan',
        ],
        'process_steps_detail' => [
            ['title' => 'Penapisan & Scoping', 'desc' => 'Identifikasi apakah kegiatan wajib AMDAL dan penentuan dampak penting hipotetik.'],
            ['title' => 'Penyusunan KA-ANDAL', 'desc' => 'Menyusun Kerangka Acuan yang memuat metodologi, ruang lingkup, dan batas studi.'],
            ['title' => 'Studi ANDAL & RKL-RPL', 'desc' => 'Pengumpulan data lapangan, analisis dampak, dan penyusunan rencana kelola & pantau.'],
            ['title' => 'Konsultasi Publik', 'desc' => 'Pelibatan masyarakat terdampak dan pemangku kepentingan sesuai ketentuan.'],
            ['title' => 'Sidang Komisi Penilai', 'desc' => 'Presentasi dan pembahasan dokumen di hadapan Komisi Penilai AMDAL.'],
            ['title' => 'Persetujuan Lingkungan', 'desc' => 'Penerbitan Surat Persetujuan Lingkungan + kewajiban pelaporan RKL-RPL berkala.'],
        ],
        'sub_services' => [
            'ka-andal' => [
                'title' => 'Penyusunan KA-ANDAL (Kerangka Acuan)',
                'short_description' => 'Penyusunan dokumen Kerangka Acuan ANDAL sebagai tahap awal proses AMDAL yang menentukan lingkup studi.',
                'long_description' => 'KA-ANDAL (Kerangka Acuan Analisis Dampak Lingkungan) adalah dokumen awal dalam proses AMDAL yang memuat ruang lingkup dan kedalaman kajian. Dokumen ini menentukan dampak penting hipotetik yang akan dikaji, metode studi, batas wilayah studi, dan jangka waktu studi. KA-ANDAL harus mendapat persetujuan dari Komisi Penilai AMDAL sebelum studi ANDAL dapat dimulai. Tim kami menyusun KA-ANDAL berdasarkan data primer dan sekunder, pelibatan masyarakat, serta analisis rona lingkungan awal.',
                'icon' => 'fa-file-signature',
                'meta_keywords' => 'ka-andal, kerangka acuan andal, penyusunan ka-andal, dokumen ka-andal, tahap awal amdal',
                'process_steps' => ['Pengumpulan data rona lingkungan awal', 'Identifikasi dampak penting hipotetik', 'Pelibatan masyarakat (konsultasi publik)', 'Penyusunan dokumen KA-ANDAL', 'Pengajuan ke Komisi Penilai', 'Revisi & persetujuan KA-ANDAL'],
                'requirements' => ['Dokumen rencana usaha/kegiatan', 'Data lokasi & peta situasi', 'Profil perusahaan & NPWP', 'Tim penyusun bersertifikat AMDAL'],
                'duration' => '30-60 Hari',
            ],
            'andal-rkl-rpl' => [
                'title' => 'Penyusunan ANDAL, RKL-RPL',
                'short_description' => 'Penyusunan dokumen inti AMDAL: studi analisis dampak lingkungan beserta rencana pengelolaan dan pemantauan.',
                'long_description' => 'ANDAL (Analisis Dampak Lingkungan Hidup) adalah studi mendalam tentang dampak penting kegiatan terhadap lingkungan, sementara RKL (Rencana Pengelolaan Lingkungan) dan RPL (Rencana Pemantauan Lingkungan) memuat upaya mitigasi dan program monitoring yang harus dilaksanakan. Penyusunan dokumen ini meliputi survei lapangan komprehensif, pengambilan sampel lingkungan, analisis laboratorium, pemodelan dampak, evaluasi dampak besar dan penting, serta formulasi rencana pengelolaan yang realistis dan terukur.',
                'icon' => 'fa-book-open',
                'meta_keywords' => 'andal rkl rpl, penyusunan andal, rencana kelola lingkungan, rencana pemantauan lingkungan',
                'process_steps' => ['Survei lapangan & pengambilan sampel', 'Analisis laboratorium', 'Pemodelan & prakiraan dampak', 'Evaluasi dampak besar & penting', 'Penyusunan RKL-RPL', 'Penilaian oleh Komisi AMDAL', 'Persetujuan lingkungan'],
                'requirements' => ['KA-ANDAL yang telah disetujui', 'Data baseline lingkungan', 'Hasil analisis laboratorium', 'Tim penyusun AMDAL bersertifikat'],
                'duration' => '90-180 Hari',
            ],
            'delh-dplh' => [
                'title' => 'DELH-DPLH (Dokumen Evaluasi & Pengelolaan)',
                'short_description' => 'Penyusunan DELH/DPLH untuk kegiatan yang sudah berjalan namun belum memiliki dokumen lingkungan.',
                'long_description' => 'DELH (Dokumen Evaluasi Lingkungan Hidup) dan DPLH (Dokumen Pengelolaan Lingkungan Hidup) adalah dokumen pengganti bagi kegiatan yang sudah beroperasi sebelum berlakunya kewajiban AMDAL atau UKL-UPL. DELH diperuntukkan bagi kegiatan yang seharusnya wajib AMDAL, sedangkan DPLH untuk kegiatan yang seharusnya wajib UKL-UPL. Dokumen ini memuat evaluasi dampak yang telah terjadi dan rencana pengelolaan ke depan.',
                'icon' => 'fa-clipboard-check',
                'meta_keywords' => 'delh, dplh, dokumen evaluasi lingkungan, dokumen pengelolaan lingkungan hidup',
                'process_steps' => ['Evaluasi kondisi lingkungan eksisting', 'Identifikasi dampak yang telah terjadi', 'Penyusunan rencana pengelolaan', 'Penyusunan rencana pemantauan', 'Pengajuan ke instansi lingkungan', 'Persetujuan DELH/DPLH'],
                'requirements' => ['Bukti kegiatan telah beroperasi', 'Data kondisi lingkungan terkini', 'Profil perusahaan & NIB', 'Laporan kegiatan pengelolaan lingkungan yang sudah dilakukan'],
                'duration' => '60-90 Hari',
            ],
            'pertek-lingkungan' => [
                'title' => 'PERTEK (Persetujuan Teknis Lingkungan)',
                'short_description' => 'Pengurusan Persetujuan Teknis untuk pembuangan limbah cair, emisi udara, dan pengelolaan limbah B3.',
                'long_description' => 'Persetujuan Teknis (PERTEK) adalah izin teknis yang diperlukan untuk kegiatan pembuangan air limbah ke badan air/tanah, pelepasan emisi ke udara, dan pengelolaan limbah B3. PERTEK terintegrasi dalam perizinan berusaha berbasis risiko melalui sistem OSS-RBA. Jenisnya meliputi: PERTEK Pembuangan Air Limbah, PERTEK Emisi Udara, PERTEK Pengelolaan Limbah B3 (penyimpanan, pengumpulan, pemanfaatan, pengolahan, penimbunan), dan PERTEK Dumping ke Laut. Setiap PERTEK memerlukan kajian teknis dan verifikasi lapangan.',
                'icon' => 'fa-cogs',
                'meta_keywords' => 'pertek lingkungan, persetujuan teknis lingkungan, pertek limbah, pertek emisi, pertek air limbah',
                'process_steps' => ['Identifikasi jenis PERTEK yang diperlukan', 'Penyusunan kajian teknis', 'Persiapan dokumen pendukung', 'Pengajuan melalui OSS-RBA', 'Verifikasi teknis lapangan', 'Penerbitan PERTEK'],
                'requirements' => ['NIB aktif di OSS-RBA', 'Persetujuan lingkungan (AMDAL/UKL-UPL)', 'Kajian teknis sesuai jenis PERTEK', 'Data teknis instalasi pengolahan'],
                'duration' => '30-90 Hari',
            ],
            'amdal-manufaktur' => [
                'title' => 'AMDAL untuk Industri Manufaktur',
                'short_description' => 'Jasa penyusunan AMDAL khusus industri manufaktur: pabrik, kawasan industri, dan fasilitas produksi.',
                'long_description' => 'Industri manufaktur dengan kapasitas produksi besar atau menggunakan bahan berbahaya wajib memiliki AMDAL. Kajian AMDAL manufaktur mencakup dampak dari proses produksi (emisi, limbah cair, limbah padat/B3), kebisingan, lalu lintas, dan dampak sosial-ekonomi terhadap masyarakat sekitar. Tim kami berpengalaman menangani AMDAL untuk berbagai jenis industri manufaktur termasuk kimia, tekstil, makanan-minuman, otomotif, elektronik, dan konstruksi material.',
                'icon' => 'fa-industry',
                'meta_keywords' => 'amdal manufaktur, amdal pabrik, amdal kawasan industri, amdal industri kimia, amdal industri makanan',
                'process_steps' => ['Penapisan & klasifikasi kegiatan', 'Penyusunan KA-ANDAL', 'Survei baseline lingkungan manufaktur', 'Prakiraan dampak proses produksi', 'Penyusunan ANDAL & RKL-RPL', 'Penilaian & persetujuan'],
                'requirements' => ['Rencana bisnis/feasibility study', 'Data kapasitas & proses produksi', 'Bahan baku & output produksi', 'Layout pabrik & site plan'],
                'duration' => '120-240 Hari',
            ],
            'amdal-pertambangan' => [
                'title' => 'AMDAL untuk Pertambangan & Energi',
                'short_description' => 'Jasa penyusunan AMDAL untuk sektor pertambangan mineral, batubara, migas, dan pembangkit energi.',
                'long_description' => 'Sektor pertambangan dan energi memiliki potensi dampak lingkungan yang sangat signifikan sehingga AMDAL menjadi persyaratan mutlak. Kajian mencakup dampak terhadap bentang alam, hidrologi, kualitas air & udara, biodiversitas, serta dampak sosial terhadap masyarakat adat dan lokal. Tim kami memiliki pengalaman dalam AMDAL tambang mineral logam & non-logam, tambang batubara, eksplorasi & eksploitasi migas, PLTU, PLTG, PLTA, dan pembangkit energi terbarukan.',
                'icon' => 'fa-gem',
                'meta_keywords' => 'amdal pertambangan, amdal tambang, amdal batubara, amdal migas, amdal energi, amdal pltu',
                'process_steps' => ['Penapisan & penentuan lingkup', 'Studi baseline geologi & hidrologi', 'Kajian biodiversitas & sosial', 'Prakiraan dampak operasi tambang', 'Rencana rehabilitasi lahan', 'Penilaian & persetujuan lingkungan'],
                'requirements' => ['IUP/WIUP atau izin eksplorasi', 'Data geologi & cadangan', 'Rencana tata ruang pertambangan', 'Rencana reklamasi & pasca-tambang'],
                'duration' => '150-300 Hari',
            ],
            'amdal-infrastruktur' => [
                'title' => 'AMDAL untuk Infrastruktur & Properti',
                'short_description' => 'Jasa penyusunan AMDAL untuk proyek infrastruktur: jalan tol, pelabuhan, bandara, dan pengembangan properti.',
                'long_description' => 'Proyek infrastruktur berskala besar seperti jalan tol, jembatan, pelabuhan, bandara, bendungan, kawasan perumahan/komersial, dan pusat perbelanjaan wajib memiliki AMDAL. Kajian mencakup dampak pembangunan terhadap lalu lintas, drainase, ruang terbuka hijau, resapan air, kebisingan, kualitas udara, serta dampak sosial berupa relokasi dan perubahan mata pencaharian. Kami berpengalaman menangani AMDAL proyek infrastruktur dengan skala mulai dari ratusan hingga ribuan hektar.',
                'icon' => 'fa-road',
                'meta_keywords' => 'amdal infrastruktur, amdal jalan tol, amdal pelabuhan, amdal properti, amdal perumahan, amdal bandara',
                'process_steps' => ['Penapisan tipe kegiatan', 'Studi baseline lingkungan & sosial', 'Analisis dampak lalu lintas & drainase', 'Prakiraan dampak konstruksi & operasi', 'Rencana pengelolaan lingkungan', 'Penilaian & persetujuan'],
                'requirements' => ['Studi kelayakan proyek (FS)', 'Site plan & masterplan', 'Data lalu lintas & drainase', 'Izin lokasi/penetapan lokasi'],
                'duration' => '120-240 Hari',
            ],
        ],
        'faq' => [
            ['q' => 'Berapa biaya jasa pengurusan AMDAL?', 'a' => 'Biaya AMDAL bervariasi tergantung skala kegiatan, lokasi, dan kompleksitas dampak. Kisaran umum mulai dari Rp 150 juta hingga Rp 1 miliar+. Untuk estimasi tepat, hubungi kami untuk konsultasi gratis.'],
            ['q' => 'Berapa lama proses penyusunan AMDAL?', 'a' => 'Proses lengkap AMDAL (dari KA-ANDAL hingga persetujuan lingkungan) umumnya 6-12 bulan. Faktor utama: kompleksitas dampak, kecepatan proses penilaian komisi, dan partisipasi masyarakat.'],
            ['q' => 'Apa perbedaan AMDAL dan UKL-UPL?', 'a' => 'AMDAL wajib untuk kegiatan berdampak besar & penting (industri besar, pertambangan, infrastruktur). UKL-UPL untuk kegiatan berdampak tidak signifikan (usaha menengah). AMDAL lebih kompleks, melibatkan komisi penilai dan pelibatan masyarakat.'],
            ['q' => 'Siapa yang berwenang menyusun AMDAL?', 'a' => 'AMDAL harus disusun oleh tim penyusun yang memiliki sertifikat kompetensi AMDAL (KTPA). Bizmark.ID memiliki tim bersertifikat dengan keahlian multidisiplin: fisika-kimia, biologi, sosial-ekonomi, kesehatan masyarakat, dan K3.'],
            ['q' => 'Apa risiko jika tidak memiliki AMDAL?', 'a' => 'Tanpa AMDAL, perusahaan tidak dapat memperoleh persetujuan lingkungan yang merupakan syarat perizinan berusaha. Sanksi meliputi penghentian kegiatan, denda administratif, pencabutan izin, hingga pidana sesuai UU PPLH.'],
            ['q' => 'Apakah AMDAL bisa ditolak?', 'a' => 'Ya, AMDAL bisa ditolak jika dokumen tidak memenuhi standar teknis, dampak dinilai tidak dapat dikelola, atau terdapat penolakan kuat dari masyarakat. Inilah pentingnya menggunakan jasa profesional berpengalaman.'],
            ['q' => 'Apa metodologi analisis yang digunakan Bizmark dalam penyusunan AMDAL?', 'a' => 'Bizmark menggunakan metodologi analisis terstandar meliputi: survei baseline multi-parameter (fisik-kimia, biologi, sosial-ekonomi), pemodelan dispersi (udara/air), analisis overlay GIS, matriks Leopold untuk identifikasi dampak, metode Battelle untuk evaluasi dampak, serta analisis risiko kesehatan lingkungan (ARKL). Setiap metodologi disesuaikan dengan karakteristik proyek dan persyaratan Komisi Penilai AMDAL.'],
            ['q' => 'Apa kualifikasi tim penyusun AMDAL di Bizmark?', 'a' => 'Tim penyusun Bizmark terdiri dari tenaga ahli bersertifikat KTPA (Kompetensi Tenaga Penyusun AMDAL) dengan latar belakang S1-S2 di bidang lingkungan, biologi, kimia, teknik sipil, dan kesehatan masyarakat. Ketua tim memiliki pengalaman 10+ tahun menangani 50+ proyek AMDAL di sektor manufaktur, pertambangan, infrastruktur, dan energi.'],
        ],
    ],
    'ukl-upl' => [
        'title' => 'Jasa Pengurusan UKL-UPL Profesional — Cepat, Mudah & Patuh Hukum',
        'slug' => 'ukl-upl',
        'short_description' => 'Panduan lengkap & jasa pengurusan UKL-UPL: syarat, prosedur, contoh, estimasi biaya, dan pendampingan end-to-end oleh tim konsultan berpengalaman.',
        'long_description' => 'Bizmark.id menyediakan jasa pengurusan UKL-UPL (Upaya Pengelolaan Lingkungan Hidup dan Upaya Pemantauan Lingkungan Hidup) secara end-to-end untuk kegiatan usaha skala kecil-menengah yang tidak wajib AMDAL. Tim konsultan berpengalaman >10 tahun mendampingi dari konsultasi awal, identifikasi dampak, penyusunan dokumen, pengajuan melalui OSS-RBA dan DLH, hingga persetujuan lingkungan terbit. UKL-UPL bukan sekadar dokumen kepatuhan — ini adalah alat strategis pengelolaan dan pemantauan lingkungan yang efektif. Proses cepat 30-60 hari, biaya terjangkau mulai Rp 15 juta, dan kepatuhan penuh terhadap PP No. 22/2021 dan Permen LHK No. 4/2021.',
        'icon' => 'fa-file-alt',
        'color' => '#9333EA',
        'meta_keywords' => 'jasa pengurusan ukl-upl, pengurusan ukl upl, biaya ukl upl, syarat ukl upl, prosedur ukl upl, konsultan ukl upl, contoh ukl upl, ukl upl adalah, perbedaan ukl-upl dan amdal, dokumen ukl upl, perizinan lingkungan, upaya pengelolaan lingkungan hidup',
        'category' => 'LINGKUNGAN',
        'price_range' => 'Mulai Rp 15 Jt',
        'process_time' => '30-60 Hari',
        'key_features' => [
            'Penyusunan formulir UKL-UPL sesuai Permen LHK yang berlaku',
            'Identifikasi dampak dan rencana pengelolaan & pemantauan',
            'Koordinasi dengan DLHK untuk proses persetujuan',
            'Penyusunan SPPL untuk usaha kecil berdampak ringan',
            'Pendampingan monitoring & pelaporan lingkungan berkala',
            'Konsultasi pra-pengajuan untuk memastikan kelengkapan dokumen',
        ],
        'documents_required' => [
            'NIB / Izin Usaha',
            'Akta pendirian & perubahan perusahaan',
            'NPWP perusahaan',
            'Izin lokasi / kesesuaian tata ruang (KKPR)',
            'Deskripsi detail kegiatan usaha',
            'Denah lokasi & peta situasi',
            'Neraca air / neraca massa (jika relevan)',
        ],
        'process_steps_detail' => [
            ['title' => 'Analisis Kegiatan', 'desc' => 'Evaluasi jenis usaha untuk menentukan apakah perlu SPPL, UKL-UPL, atau AMDAL.'],
            ['title' => 'Identifikasi Dampak', 'desc' => 'Pemetaan dampak lingkungan potensial dari kegiatan operasional.'],
            ['title' => 'Penyusunan Dokumen', 'desc' => 'Formulir UKL-UPL atau SPPL disusun sesuai format dan standar regulasi.'],
            ['title' => 'Pengajuan & Review', 'desc' => 'Submit dokumen ke DLHK dan pendampingan revisi jika diperlukan.'],
            ['title' => 'Persetujuan Terbit', 'desc' => 'Rekomendasi UKL-UPL atau registrasi SPPL diterbitkan oleh instansi berwenang.'],
        ],
        'sub_services' => [
            'sppl' => [
                'title' => 'SPPL (Surat Pernyataan Pengelolaan Lingkungan)',
                'short_description' => 'Penyusunan SPPL untuk usaha mikro dan kecil yang berdampak lingkungan ringan.',
                'long_description' => 'SPPL (Surat Pernyataan Kesanggupan Pengelolaan dan Pemantauan Lingkungan Hidup) adalah dokumen lingkungan paling sederhana, diperuntukkan bagi usaha/kegiatan yang tidak memerlukan AMDAL maupun UKL-UPL. SPPL berisi pernyataan kesanggupan pemrakarsa untuk mengelola dan memantau dampak lingkungan dari kegiatannya. Meskipun prosesnya sederhana, SPPL tetap harus memuat informasi yang akurat tentang jenis usaha, lokasi, dampak potensial, dan upaya pengelolaan yang akan dilakukan.',
                'icon' => 'fa-file-contract',
                'meta_keywords' => 'sppl, surat pernyataan pengelolaan lingkungan, sppl usaha kecil, dokumen sppl',
                'process_steps' => ['Identifikasi jenis & skala kegiatan', 'Penentuan kategori risiko di OSS', 'Penyusunan dokumen SPPL', 'Pengunggahan ke sistem OSS', 'Verifikasi & persetujuan'],
                'requirements' => ['NIB dari OSS', 'KTP pemrakarsa', 'Lokasi & deskripsi kegiatan', 'Identifikasi dampak lingkungan ringan'],
                'duration' => '7-14 Hari',
            ],
            'rkl-rpl' => [
                'title' => 'RKL-RPL (Rencana Kelola & Pantau Lingkungan)',
                'short_description' => 'Penyusunan dokumen Rencana Pengelolaan dan Pemantauan Lingkungan Hidup detail.',
                'long_description' => 'RKL (Rencana Pengelolaan Lingkungan Hidup) dan RPL (Rencana Pemantauan Lingkungan Hidup) merupakan bagian integral dari dokumen UKL-UPL. RKL memuat upaya pengelolaan untuk setiap dampak lingkungan yang teridentifikasi, termasuk jadwal pelaksanaan dan institusi pengelola. RPL memuat metode pemantauan, frekuensi, lokasi, dan parameter yang dipantau. Dokumen ini menjadi acuan operasional perusahaan dalam menjalankan kewajiban lingkungan.',
                'icon' => 'fa-tasks',
                'meta_keywords' => 'rkl rpl, rencana kelola lingkungan, rencana pemantauan lingkungan',
                'process_steps' => ['Identifikasi dampak lingkungan', 'Formulasi upaya pengelolaan', 'Penentuan program pemantauan', 'Penyusunan matriks RKL-RPL', 'Konsultasi dengan DLHK', 'Finalisasi dokumen'],
                'requirements' => ['Dokumen UKL-UPL yang telah disetujui', 'Data teknis operasional perusahaan', 'Layout fasilitas & titik pemantauan'],
                'duration' => '14-30 Hari',
            ],
            'monitoring-ukl-upl' => [
                'title' => 'Laporan Monitoring UKL-UPL',
                'short_description' => 'Penyusunan laporan pemantauan lingkungan berkala sesuai ketentuan UKL-UPL yang telah disetujui.',
                'long_description' => 'Setelah UKL-UPL disetujui, perusahaan wajib melaksanakan pemantauan lingkungan secara berkala (umumnya setiap 6 bulan) dan melaporkannya ke DLHK. Laporan monitoring mencakup hasil pengukuran parameter lingkungan (kualitas air limbah, emisi udara, kebisingan, getaran), pelaksanaan upaya pengelolaan, dan evaluasi efektivitas. Tim kami membantu pengambilan sampel, analisis laboratorium terakreditasi, penyusunan laporan, dan pendampingan pelaporan ke instansi.',
                'icon' => 'fa-chart-bar',
                'meta_keywords' => 'laporan monitoring ukl-upl, pemantauan lingkungan, laporan lingkungan berkala',
                'process_steps' => ['Pengambilan sampel lingkungan', 'Analisis di laboratorium terakreditasi', 'Evaluasi kepatuhan terhadap baku mutu', 'Penyusunan laporan monitoring', 'Pengajuan ke DLHK', 'Rekomendasi perbaikan (jika diperlukan)'],
                'requirements' => ['Dokumen UKL-UPL yang telah disetujui', 'Akses ke titik sampling', 'Data operasional 6 bulan terakhir'],
                'duration' => '14-21 Hari',
            ],
        ],
        'faq' => [
            ['q' => 'Apa itu UKL-UPL dan siapa yang wajib membuatnya?', 'a' => 'UKL-UPL (Upaya Pengelolaan Lingkungan Hidup dan Upaya Pemantauan Lingkungan Hidup) adalah dokumen lingkungan wajib bagi usaha/kegiatan skala menengah yang tidak termasuk kategori wajib AMDAL berdasarkan PP No. 22 Tahun 2021 dan Permen LHK No. 4 Tahun 2021. Contoh: industri rumah tangga, perhotelan, perkantoran, retail, dan sektor jasa.'],
            ['q' => 'Berapa biaya jasa pengurusan UKL-UPL?', 'a' => 'Biaya jasa pengurusan UKL-UPL umumnya berkisar Rp 15-75 juta tergantung jenis kegiatan, lokasi, dan kompleksitas. Kami menawarkan harga terjangkau dengan konsultasi awal gratis untuk estimasi detail.'],
            ['q' => 'Berapa lama proses pengurusan UKL-UPL?', 'a' => 'Proses penyusunan dan persetujuan UKL-UPL umumnya 30-60 hari kerja. Penyusunan dokumen 5-7 hari, pengajuan dan verifikasi DLHK 7-14 hari, total lebih cepat dibanding AMDAL.'],
            ['q' => 'Apa perbedaan UKL-UPL, AMDAL, dan SPPL?', 'a' => 'AMDAL untuk kegiatan berdampak besar (komisi penilai, 6-12 bulan). UKL-UPL untuk dampak menengah (formulir standar, 30-60 hari). SPPL untuk usaha mikro/kecil risiko rendah (surat pernyataan, 7-14 hari). Penentuan berdasarkan Permen LHK No. 4 Tahun 2021.'],
            ['q' => 'Apa dasar hukum kewajiban UKL-UPL?', 'a' => 'UU No. 32 Tahun 2009 tentang PPLH, UU No. 6 Tahun 2023 tentang Cipta Kerja, PP No. 22 Tahun 2021 tentang Penyelenggaraan PPLH, Permen LHK No. 4 Tahun 2021, dan peraturan daerah setempat tentang perlindungan lingkungan.'],
            ['q' => 'Apakah Bizmark.id bisa mendampingi proses pengajuan UKL-UPL melalui OSS?', 'a' => 'Ya. Kami mendampingi seluruh proses — dari konsultasi awal, penyusunan dokumen, upload ke OSS-RBA, koordinasi dengan DLH/DLHK, sampai persetujuan lingkungan terbit. Anda tidak perlu repot mengurus sendiri.'],
            ['q' => 'Apa sanksi jika tidak memiliki UKL-UPL?', 'a' => 'Sanksi meliputi teguran tertulis, pembekuan kegiatan usaha, denda administratif hingga ratusan juta rupiah, dan pencabutan NIB/izin operasional berdasarkan UU No. 32/2009 dan PP No. 22/2021.'],
            ['q' => 'Apakah UKL-UPL memerlukan pemantauan berkala?', 'a' => 'Ya, perusahaan wajib melaporkan pelaksanaan pengelolaan dan pemantauan lingkungan setiap 6 bulan ke DLHK melalui sistem SIMPEL. Kami juga menyediakan jasa penyusunan laporan monitoring.'],
        ],
    ],
    'oss-nib' => [
        'title' => 'Jasa Konsultan OSS NIB Profesional — Proses 1-3 Hari, Mulai Rp 1,5 Jt',
        'slug' => 'oss-nib',
        'short_description' => 'Konsultan OSS NIB terpercaya: pengurusan NIB cepat 1-3 hari, pemilihan KBLI, pembuatan akun OSS-RBA, hingga izin usaha berbasis risiko. Mulai Rp 1,5 juta, konsultasi gratis.',
        'long_description' => 'Bizmark.id adalah konsultan OSS NIB profesional yang telah membantu ratusan perusahaan mengurus Nomor Induk Berusaha (NIB) melalui sistem Online Single Submission (OSS-RBA). NIB berfungsi sebagai identitas resmi pelaku usaha yang menggantikan TDP, API, dan Hak Akses Ketenagakerjaan. Layanan kami mencakup: konsultasi & pemilihan KBLI yang tepat, pembuatan akun OSS-RBA, input data & pengajuan NIB, pengurusan Sertifikat Standar & izin usaha berbasis risiko, hingga pendampingan pemenuhan komitmen perizinan. Biaya mulai Rp 1,5 juta dengan proses hanya 1-3 hari kerja. Dasar hukum: PP No. 5 Tahun 2021 tentang Perizinan Berusaha Berbasis Risiko dan UU No. 6 Tahun 2023 tentang Cipta Kerja.',
        'icon' => 'fa-globe',
        'color' => '#F59E0B',
        'meta_keywords' => 'konsultan oss nib, jasa pengurusan nib, biaya nib, cara membuat nib, pengurusan nib online, oss rba, nomor induk berusaha, izin usaha oss, jasa konsultan nib, nib perorangan, nib badan usaha, kbli oss',
        'category' => 'PERIZINAN USAHA',
        'featured' => true,
        'price' => 'Rp 1,5 Jt',
        'price_range' => 'Mulai Rp 1,5 Jt',
        'badge' => 'Terfavorit',
        'process_time' => '1-3 Hari',
        'key_features' => [
            'Registrasi dan penerbitan NIB melalui sistem OSS-RBA',
            'Pemilihan KBLI yang tepat sesuai bidang usaha',
            'Klasifikasi tingkat risiko usaha (rendah/menengah/tinggi)',
            'Pengurusan izin turunan: sertifikat standar & izin komersial',
            'Pendampingan pemenuhan komitmen pasca-NIB',
            'Konsultasi perizinan berusaha berbasis risiko end-to-end',
        ],
        'documents_required' => [
            'KTP & NIK pemilik/direktur',
            'NPWP perorangan atau badan usaha',
            'Akta pendirian perusahaan (untuk badan usaha)',
            'SK Kemenkumham (untuk PT)',
            'Alamat domisili usaha yang jelas',
            'Deskripsi kegiatan usaha & KBLI',
        ],
        'process_steps_detail' => [
            ['title' => 'Konsultasi KBLI', 'desc' => 'Analisis kegiatan usaha dan pemilihan kode KBLI paling tepat.'],
            ['title' => 'Registrasi Akun OSS', 'desc' => 'Pembuatan akun di sistem OSS-RBA menggunakan NIK penanggungjawab.'],
            ['title' => 'Input Data & Pengajuan', 'desc' => 'Pengisian data usaha, lokasi, dan kapasitas pada sistem OSS.'],
            ['title' => 'Penerbitan NIB', 'desc' => 'NIB terbit secara elektronik beserta perizinan dasar.'],
            ['title' => 'Pemenuhan Komitmen', 'desc' => 'Pendampingan penyelesaian komitmen perizinan sesuai tingkat risiko.'],
        ],
        'sub_services' => [
            'nib-perorangan' => [
                'title' => 'NIB Perorangan (Usaha Mikro & Kecil)',
                'short_description' => 'Pengurusan NIB untuk pelaku usaha perorangan, UMKM, dan usaha mikro-kecil melalui OSS.',
                'long_description' => 'NIB Perorangan diperuntukkan bagi pelaku usaha yang menjalankan kegiatan secara perorangan tanpa badan hukum formal. Melalui sistem OSS-RBA, pendaftaran NIB perorangan menjadi lebih mudah dengan persyaratan minimal. NIB Perorangan mencakup usaha mikro dan kecil dengan kriteria tertentu berdasarkan modal usaha dan hasil penjualan tahunan.',
                'icon' => 'fa-user',
                'meta_keywords' => 'nib perorangan, nib umkm, nib usaha mikro, oss perorangan, izin usaha perorangan',
                'process_steps' => ['Registrasi akun OSS-RBA', 'Input data pelaku usaha', 'Pemilihan KBLI yang sesuai', 'Verifikasi data & NIK', 'Penerbitan NIB perorangan', 'Pemenuhan komitmen (jika ada)'],
                'requirements' => ['KTP & NIK valid', 'NPWP (untuk usaha tertentu)', 'Alamat domisili usaha', 'Deskripsi kegiatan usaha'],
                'duration' => '1-3 Hari',
            ],
            'nib-badan-usaha' => [
                'title' => 'NIB Badan Usaha (PT, CV, Yayasan)',
                'short_description' => 'Pengurusan NIB untuk badan usaha: PT, CV, Firma, Koperasi, Yayasan melalui OSS-RBA.',
                'long_description' => 'NIB Badan Usaha diperlukan untuk perusahaan berbadan hukum (PT, Yayasan) maupun badan usaha lain (CV, Firma, Koperasi) yang menjalankan kegiatan komersial. Proses pendaftaran melalui OSS-RBA memerlukan data perusahaan yang valid, akta pendirian yang telah terdaftar di AHU, dan pemilihan KBLI yang tepat sesuai bidang usaha. NIB badan usaha berfungsi sekaligus sebagai TDP, API, dan akses ketenagakerjaan.',
                'icon' => 'fa-building',
                'meta_keywords' => 'nib pt, nib cv, nib badan usaha, oss badan usaha, pengurusan nib perusahaan',
                'process_steps' => ['Verifikasi akta & AHU', 'Registrasi akun OSS-RBA', 'Input data perusahaan', 'Pemilihan KBLI & tingkat risiko', 'Penerbitan NIB', 'Pengurusan izin usaha berbasis risiko'],
                'requirements' => ['Akta pendirian (terdaftar di AHU)', 'NPWP perusahaan', 'NIK direktur/penanggung jawab', 'Alamat domisili perusahaan', 'Modal dasar & modal ditempatkan'],
                'duration' => '1-5 Hari',
            ],
            'izin-usaha-oss' => [
                'title' => 'Izin Usaha via OSS-RBA',
                'short_description' => 'Pengurusan izin usaha berbasis risiko melalui platform OSS-RBA termasuk pemenuhan komitmen perizinan.',
                'long_description' => 'Sistem perizinan berusaha berbasis risiko (OSS-RBA) mengklasifikasikan kegiatan usaha ke dalam 4 tingkat risiko: Rendah (cukup NIB), Menengah Rendah (NIB + Sertifikat Standar), Menengah Tinggi (NIB + Sertifikat Standar terverifikasi), dan Tinggi (NIB + Izin). Kami membantu menentukan tingkat risiko KBLI kegiatan Anda, menyiapkan pemenuhan komitmen, koordinasi verifikasi/inspeksi, hingga izin usaha terbit dan operasional.',
                'icon' => 'fa-clipboard-list',
                'meta_keywords' => 'izin usaha oss, oss-rba, perizinan berbasis risiko, sertifikat standar, izin berusaha',
                'process_steps' => ['Analisis KBLI & tingkat risiko', 'Pengajuan di OSS-RBA', 'Penyiapan dokumen komitmen', 'Pemenuhan persyaratan teknis', 'Verifikasi/inspeksi (jika diperlukan)', 'Penerbitan izin usaha'],
                'requirements' => ['NIB aktif', 'Dokumen lingkungan (sesuai risiko)', 'Standar teknis yang berlaku', 'Sertifikat/izin teknis terkait'],
                'duration' => '7-30 Hari',
            ],
        ],
        'faq' => [
            ['q' => 'Apa itu NIB dan mengapa wajib dimiliki?', 'a' => 'NIB (Nomor Induk Berusaha) adalah identitas resmi pelaku usaha yang diterbitkan melalui sistem OSS-RBA. Berdasarkan PP No. 5 Tahun 2021, semua pelaku usaha wajib memiliki NIB sebelum menjalankan kegiatan usaha. NIB menggantikan fungsi SIUP, TDP, dan API.'],
            ['q' => 'Berapa biaya jasa konsultan OSS NIB di Bizmark.id?', 'a' => 'Biaya pengurusan NIB mulai dari Rp 1,5 juta untuk NIB perorangan/UMKM. Untuk badan usaha (PT, CV) mulai Rp 3 juta, dan paket lengkap NIB + izin usaha berbasis risiko mulai Rp 5 juta. Konsultasi awal gratis.'],
            ['q' => 'Berapa lama proses penerbitan NIB?', 'a' => 'NIB dapat terbit dalam 1-3 hari kerja setelah data lengkap. Untuk usaha berisiko rendah, penerbitan bisa instan pada hari yang sama. Dengan jasa konsultan profesional, proses lebih cepat karena data divalidasi sejak awal.'],
            ['q' => 'Apa saja yang termasuk dalam layanan konsultan OSS NIB?', 'a' => 'Layanan kami mencakup: konsultasi & pemilihan KBLI, pembuatan akun OSS-RBA, input data & pengajuan NIB, pengurusan Sertifikat Standar/Izin, pendampingan pemenuhan komitmen, hingga koordinasi dengan instansi terkait. End-to-end service.'],
            ['q' => 'Apa bedanya NIB perorangan dan NIB badan usaha?', 'a' => 'NIB perorangan untuk usaha mikro/kecil tanpa badan hukum (cukup KTP & NPWP). NIB badan usaha untuk PT, CV, Firma, Koperasi (memerlukan akta, SK AHU, NPWP badan). Proses pembuatan akun OSS dan persyaratan dokumen berbeda.'],
            ['q' => 'Apa itu KBLI dan mengapa pemilihan KBLI penting?', 'a' => 'KBLI (Klasifikasi Baku Lapangan Usaha Indonesia) adalah kode 5 digit yang menentukan jenis kegiatan usaha. Pemilihan KBLI yang tepat menentukan tingkat risiko, jenis izin yang diperlukan, dan komitmen perizinan. Salah pilih KBLI bisa menyebabkan penolakan atau izin tidak sesuai.'],
            ['q' => 'Apa itu tingkat risiko dalam OSS-RBA?', 'a' => 'OSS-RBA mengkategorikan usaha berdasarkan risiko: Rendah (cukup NIB), Menengah Rendah (NIB + Sertifikat Standar), Menengah Tinggi (NIB + Sertifikat Standar terverifikasi), dan Tinggi (NIB + Izin lengkap termasuk AMDAL/UKL-UPL). Klasifikasi ditentukan oleh KBLI.'],
            ['q' => 'Apa sanksi jika tidak memiliki NIB?', 'a' => 'Usaha tanpa NIB melanggar PP 5/2021 dan dapat dikenai sanksi: peringatan tertulis, penghentian sementara kegiatan, denda administratif, hingga penutupan permanen. Selain itu, tidak bisa mengakses tender pemerintah, ekspor-impor, dan program bantuan UMKM.'],
        ],
    ],
    'pbg-slf' => [
        'title' => 'PBG / SLF',
        'slug' => 'pbg-slf',
        'short_description' => 'Perizinan bangunan dan sertifikat kelayakan fungsi gedung',
        'long_description' => 'Persetujuan Bangunan Gedung (PBG) dan Sertifikat Laik Fungsi (SLF) adalah persyaratan wajib untuk setiap pembangunan dan pengoperasian gedung di Indonesia sesuai UU No. 28 Tahun 2002 tentang Bangunan Gedung. PBG diperlukan sebelum memulai konstruksi, sementara SLF diterbitkan setelah bangunan selesai dan lulus inspeksi kelaikan fungsi. Tanpa SLF, bangunan tidak dapat beroperasi secara legal dan Anda tidak dapat mengurus izin operasional lainnya. Kami menangani seluruh proses mulai dari penyiapan dokumen teknis (gambar arsitektur, struktur, MEP), koordinasi dengan dinas PU/tata ruang, hingga pendampingan inspeksi lapangan.',
        'icon' => 'fa-building',
        'color' => '#0A66C2',
        'meta_keywords' => 'pbg, slf, izin mendirikan bangunan, sertifikat laik fungsi',
        'category' => 'BANGUNAN',
        'price_range' => 'Mulai Rp 20 Jt',
        'process_time' => '30-60 Hari',
        'key_features' => [
            'Pengurusan PBG melalui sistem SIMBG untuk bangunan baru & renovasi',
            'Penyiapan gambar arsitektur, struktur, MEP & proteksi kebakaran',
            'Koordinasi dengan Dinas PU/Pekerjaan Umum & Tata Ruang',
            'Pendampingan pemeriksaan oleh Tim Profesi Ahli (TPA/TPT)',
            'Pengurusan SLF untuk bangunan yang sudah beroperasi',
            'Penyusunan Andalalin untuk bangunan berdampak lalu lintas',
        ],
        'documents_required' => [
            'Sertifikat hak atas tanah / izin penggunaan tanah',
            'Gambar arsitektur & gambar struktur lengkap',
            'Perhitungan struktur oleh insinyur bersertifikat',
            'Gambar instalasi MEP (mekanikal, elektrikal, plumbing)',
            'Rencana proteksi kebakaran',
            'Izin lokasi / KKPR (Konfirmasi Kesesuaian Pemanfaatan Ruang)',
            'KTP & NPWP pemilik bangunan',
        ],
        'process_steps_detail' => [
            ['title' => 'Konsultasi Teknis', 'desc' => 'Evaluasi kebutuhan PBG/SLF berdasarkan jenis dan fungsi bangunan.'],
            ['title' => 'Penyiapan Dokumen Teknis', 'desc' => 'Gambar arsitektur, struktur, MEP, dan proteksi kebakaran disiapkan.'],
            ['title' => 'Pengajuan SIMBG', 'desc' => 'Submit dokumen melalui Sistem Informasi Manajemen Bangunan Gedung.'],
            ['title' => 'Pemeriksaan TPA/TPT', 'desc' => 'Tim Profesi Ahli memeriksa kesesuaian desain dengan standar teknis.'],
            ['title' => 'Penerbitan PBG/SLF', 'desc' => 'PBG terbit setelah lolos pemeriksaan; SLF setelah bangunan selesai & inspeksi.'],
        ],
        'sub_services' => [
            'pbg-bangunan-gedung' => [
                'title' => 'PBG (Persetujuan Bangunan Gedung)',
                'short_description' => 'Pengurusan Persetujuan Bangunan Gedung untuk konstruksi bangunan baru, renovasi, atau perubahan fungsi.',
                'long_description' => 'Persetujuan Bangunan Gedung (PBG) menggantikan IMB (Izin Mendirikan Bangunan) sejak berlakunya PP No. 16 Tahun 2021 tentang Bangunan Gedung. PBG wajib dimiliki sebelum memulai pembangunan baru, renovasi besar, atau perubahan fungsi bangunan. Proses PBG meliputi konsultasi perencanaan, pemeriksaan desain (arsitektur, struktur, MEP, proteksi kebakaran), dan penerbitan persetujuan.',
                'icon' => 'fa-hard-hat',
                'meta_keywords' => 'pbg, persetujuan bangunan gedung, izin bangunan, pengganti imb, pbg baru',
                'process_steps' => ['Konsultasi perencanaan teknis', 'Penyiapan gambar arsitektur & struktur', 'Perhitungan struktur & MEP', 'Pengajuan PBG melalui SIMBG', 'Pemeriksaan desain oleh TPA/TPT', 'Penerbitan PBG'],
                'requirements' => ['Bukti kepemilikan/penguasaan tanah', 'Gambar arsitektur & struktur', 'Perhitungan struktur', 'Rencana MEP (Mechanical, Electrical, Plumbing)', 'Rencana proteksi kebakaran'],
                'duration' => '30-60 Hari',
            ],
            'slf-sertifikat' => [
                'title' => 'SLF (Sertifikat Laik Fungsi)',
                'short_description' => 'Pengurusan Sertifikat Laik Fungsi untuk bangunan yang telah selesai dibangun atau perpanjangan SLF.',
                'long_description' => 'Sertifikat Laik Fungsi (SLF) menyatakan bahwa bangunan gedung telah memenuhi persyaratan kelaikan fungsi: keselamatan, kesehatan, kenyamanan, dan kemudahan. SLF wajib dimiliki sebelum bangunan digunakan/difungsikan. Masa berlaku SLF: 20 tahun untuk bangunan permanen, 10 tahun untuk semi permanen, 5 tahun untuk darurat. Perpanjangan SLF memerlukan pemeriksaan berkala kondisi bangunan.',
                'icon' => 'fa-certificate',
                'meta_keywords' => 'slf, sertifikat laik fungsi, kelayakan bangunan, inspeksi bangunan, perpanjangan slf',
                'process_steps' => ['Pemeriksaan kesesuaian dengan PBG', 'Inspeksi kelaikan fungsi', 'Uji keselamatan struktur & kebakaran', 'Penyusunan laporan kelaikan', 'Penerbitan SLF', 'Pendaftaran di SIMBG'],
                'requirements' => ['PBG yang telah terbit', 'As-built drawing', 'Laporan pelaksanaan konstruksi', 'Hasil uji material & struktur', 'Sertifikat instalasi (listrik, proteksi kebakaran)'],
                'duration' => '21-45 Hari',
            ],
            'andalalin' => [
                'title' => 'Andalalin (Analisis Dampak Lalu Lintas)',
                'short_description' => 'Penyusunan dokumen Analisis Dampak Lalu Lintas wajib untuk bangunan yang berpotensi membangkitkan lalu lintas.',
                'long_description' => 'Analisis Dampak Lalu Lintas (Andalalin) wajib untuk setiap pembangunan pusat kegiatan, pemukiman, dan infrastruktur yang akan menimbulkan gangguan keamanan, keselamatan, ketertiban, dan kelancaran lalu lintas. Sesuai PP No. 32 Tahun 2011, Andalalin diperlukan untuk bangunan dengan bangkitan/tarikan perjalanan signifikan seperti pusat perbelanjaan, rumah sakit, sekolah, perkantoran besar, dan kawasan perumahan. Dokumen Andalalin memuat analisis kondisi lalu lintas eksisting, prakiraan bangkitan, simulasi dampak, dan rekomendasi penanganan.',
                'icon' => 'fa-traffic-light',
                'meta_keywords' => 'andalalin, analisis dampak lalu lintas, studi lalin, manajemen lalu lintas, andalalin gedung',
                'process_steps' => ['Survei lalu lintas eksisting', 'Analisis bangkitan & tarikan perjalanan', 'Simulasi & pemodelan lalu lintas', 'Evaluasi dampak & rekomendasi', 'Penyusunan dokumen Andalalin', 'Persetujuan dari Dinas Perhubungan'],
                'requirements' => ['Site plan bangunan', 'Data kapasitas/fungsi bangunan', 'PBG atau rencana PBG', 'Data lalu lintas sekitar lokasi'],
                'duration' => '30-60 Hari',
            ],
        ],
        'faq' => [
            ['q' => 'Apa perbedaan PBG dan IMB?', 'a' => 'PBG (Persetujuan Bangunan Gedung) menggantikan IMB sejak PP No. 16/2021. Prosesnya serupa namun PBG terintegrasi dengan sistem SIMBG dan perizinan berusaha OSS.'],
            ['q' => 'Berapa biaya pengurusan PBG?', 'a' => 'Biaya PBG terdiri dari retribusi pemerintah (tergantung luas & fungsi bangunan) dan biaya jasa konsultan. Hubungi kami untuk estimasi biaya detail.'],
            ['q' => 'Apakah renovasi memerlukan PBG?', 'a' => 'Ya, renovasi besar (mengubah struktur atau menambah lantai) memerlukan PBG baru. Renovasi kecil (cat ulang, ganti atap tanpa mengubah struktur) umumnya tidak memerlukan PBG.'],
            ['q' => 'Berapa masa berlaku SLF?', 'a' => 'SLF berlaku 20 tahun untuk bangunan permanen, 10 tahun untuk semi permanen, dan 5 tahun untuk bangunan darurat. Setelahnya perlu diperpanjang.'],
            ['q' => 'Kapan Andalalin diperlukan?', 'a' => 'Andalalin wajib untuk bangunan yang membangkitkan lalu lintas signifikan: pusat perbelanjaan, perkantoran besar, rumah sakit, sekolah, kawasan perumahan, dan fasilitas umum lainnya.'],
        ],
    ],
    'izin-operasional' => [
        'title' => 'Izin Operasional Industri',
        'slug' => 'izin-operasional',
        'short_description' => 'Kelengkapan izin untuk operasional industri manufaktur',
        'long_description' => 'Izin Operasional Industri mencakup berbagai perizinan yang diperlukan untuk menjalankan kegiatan produksi secara legal dan aman. Ini termasuk Izin Usaha Industri (IUI) yang kini terintegrasi dalam sistem OSS, izin lingkungan (UKL-UPL atau AMDAL), izin gangguan (HO), izin K3, dan izin teknis lain sesuai jenis industri. Industri makanan memerlukan sertifikasi BPOM dan Halal, industri kimia memerlukan izin B3, dan industri tertentu memerlukan Standar Nasional Indonesia (SNI). Kami memetakan seluruh kebutuhan izin Anda dan mengurusnya secara sistematis agar operasional tidak terhambat.',
        'icon' => 'fa-industry',
        'color' => '#EC4899',
        'meta_keywords' => 'izin operasional, izin industri, perizinan pabrik, compliance industri',
        'category' => 'INDUSTRI',
        'price_range' => 'Mulai Rp 10 Jt',
        'process_time' => '14-180 Hari',
        'key_features' => [
            'Pengurusan IUI & sertifikat standar industri melalui OSS-RBA',
            'Analisis KBLI dan klasifikasi risiko kegiatan industri',
            'Pendampingan sertifikasi SNI, BPOM, Halal (sesuai jenis industri)',
            'Pengurusan izin lingkungan industri (UKL-UPL / AMDAL)',
            'Audit kepatuhan & izin operasional fasilitas produksi',
            'Koordinasi multi-instansi (BKPM, Kemenperin, DLHK, Disnaker)',
        ],
        'documents_required' => [
            'Akta pendirian perusahaan & SK Kemenkumham',
            'NPWP perusahaan',
            'NIB & perizinan berusaha dari OSS',
            'Izin lokasi / KKPR',
            'Dokumen lingkungan (UKL-UPL atau AMDAL)',
            'Standar teknis produksi & layout pabrik',
            'Sertifikat kompetensi tenaga teknis (jika diperlukan)',
        ],
        'process_steps_detail' => [
            ['title' => 'Mapping Kebutuhan Izin', 'desc' => 'Identifikasi seluruh izin yang diperlukan berdasarkan jenis & skala industri.'],
            ['title' => 'Analisis KBLI & Risiko', 'desc' => 'Menentukan klasifikasi KBLI dan tingkat risiko berusaha di OSS-RBA.'],
            ['title' => 'Penyiapan Dokumen', 'desc' => 'Menyusun dokumen teknis, standar produksi, dan persyaratan administratif.'],
            ['title' => 'Pengajuan Multi-Instansi', 'desc' => 'Koordinasi pengajuan ke instansi terkait (BKPM, Kemenperin, DLHK).'],
            ['title' => 'Verifikasi & Sertifikasi', 'desc' => 'Pendampingan verifikasi lapangan dan proses sertifikasi industri.'],
            ['title' => 'Penerbitan Izin Operasional', 'desc' => 'Izin operasional terbit — seluruh legalitas industri terpenuhi.'],
        ],
        'sub_services' => [
            'iui-izin-usaha-industri' => [
                'title' => 'IUI (Izin Usaha Industri)',
                'short_description' => 'Pengurusan Izin Usaha Industri yang terintegrasi dengan sistem OSS berbasis risiko.',
                'long_description' => 'Izin Usaha Industri (IUI) adalah izin wajib bagi pelaku industri manufaktur untuk menjalankan kegiatan produksi. Sejak berlakunya sistem OSS-RBA, IUI terintegrasi dalam perizinan berusaha berbasis risiko. Tingkat risiko ditentukan berdasarkan KBLI kegiatan industri, yang menentukan apakah cukup NIB saja, memerlukan sertifikat standar, atau izin lengkap.',
                'icon' => 'fa-industry',
                'meta_keywords' => 'iui, izin usaha industri, perizinan industri, izin pabrik, izin manufaktur',
                'process_steps' => ['Analisis KBLI & klasifikasi risiko', 'Registrasi OSS-RBA', 'Penerbitan NIB + komitmen', 'Penyiapan standar teknis industri', 'Verifikasi lapangan (jika diperlukan)', 'Penerbitan IUI/sertifikat standar'],
                'requirements' => ['Akta pendirian perusahaan', 'NPWP', 'Izin lokasi/kesesuaian tata ruang', 'Dokumen lingkungan', 'Standar teknis produksi'],
                'duration' => '14-45 Hari',
            ],
            'sertifikasi-industri' => [
                'title' => 'Sertifikasi & Standar Industri',
                'short_description' => 'Pendampingan sertifikasi BPOM, Halal, SNI, dan standar industri lainnya.',
                'long_description' => 'Banyak industri memerlukan sertifikasi khusus selain izin usaha. Industri makanan/minuman wajib registrasi BPOM dan sertifikasi Halal (untuk produk halal). Produk tertentu wajib memenuhi Standar Nasional Indonesia (SNI). Kami mendampingi proses mulai dari gap analysis, penyiapan sistem & dokumen, pengujian produk, hingga perolehan sertifikat.',
                'icon' => 'fa-medal',
                'meta_keywords' => 'sertifikasi bpom, sertifikat halal, sertifikasi sni, standar industri, izin edar bpom',
                'process_steps' => ['Gap analysis terhadap standar', 'Penyiapan sistem manajemen', 'Pengujian produk', 'Pengajuan sertifikasi', 'Audit/inspeksi', 'Penerbitan sertifikat'],
                'requirements' => ['NIB & IUI aktif', 'Fasilitas produksi sesuai standar', 'SOP produksi terdokumentasi', 'Sampel produk untuk pengujian'],
                'duration' => '30-90 Hari',
            ],
            'izin-lingkungan-industri' => [
                'title' => 'Izin Lingkungan Industri',
                'short_description' => 'Paket lengkap perizinan lingkungan untuk industri: UKL-UPL/AMDAL, PERTEK, dan pelaporan berkala.',
                'long_description' => 'Setiap industri wajib memiliki dokumen lingkungan (AMDAL atau UKL-UPL) dan perizinan teknis lingkungan (PERTEK) untuk pembuangan air limbah, emisi udara, dan pengelolaan limbah B3. Kami menyediakan paket layanan lengkap mulai dari penyusunan dokumen lingkungan, pengurusan PERTEK, instalasi sistem monitoring, hingga pelaporan lingkungan berkala.',
                'icon' => 'fa-leaf',
                'meta_keywords' => 'izin lingkungan industri, amdal industri, ukl-upl pabrik, pertek industri',
                'process_steps' => ['Asesmen kebutuhan perizinan lingkungan', 'Penyusunan UKL-UPL/AMDAL', 'Pengurusan PERTEK', 'Setup sistem monitoring lingkungan', 'Pelaporan berkala ke DLHK'],
                'requirements' => ['NIB & IUI aktif', 'Data proses produksi & limbah', 'Layout fasilitas & IPAL/cerobong', 'Neraca air & bahan'],
                'duration' => '60-180 Hari',
            ],
        ],
        'faq' => [
            ['q' => 'Izin apa saja yang diperlukan untuk mendirikan pabrik?', 'a' => 'Minimal: NIB, IUI/sertifikat standar, dokumen lingkungan (AMDAL/UKL-UPL), PBG/SLF, izin K3. Untuk industri khusus: BPOM, Halal, SNI, izin B3, dan izin teknis lainnya.'],
            ['q' => 'Berapa lama proses pengurusan izin industri lengkap?', 'a' => 'Paket lengkap (NIB + IUI + lingkungan + PBG) umumnya 3-6 bulan. Kami menyusun roadmap perizinan agar prosesnya efisien dan paralel.'],
            ['q' => 'Apakah Bizmark.ID menangani sertifikasi BPOM?', 'a' => 'Ya, kami mendampingi proses registrasi BPOM untuk industri makanan, minuman, kosmetik, dan obat tradisional — dari penyiapan dokumen hingga perolehan nomor registrasi.'],
        ],
    ],
    'konsultan-lingkungan' => [
        'title' => 'Konsultan Lingkungan Hidup',
        'slug' => 'konsultan-lingkungan',
        'short_description' => 'Konsultasi dan pendampingan pengelolaan lingkungan perusahaan',
        'category' => 'LINGKUNGAN',
        'price_range' => 'Mulai Rp 15 Jt',
        'process_time' => '14 Hari - 6 Bulan',
        'long_description' => 'Konsultan Lingkungan Hidup memberikan layanan profesional untuk membantu perusahaan memenuhi kewajiban lingkungan sekaligus mengintegrasikan praktik keberlanjutan dalam operasi bisnis. Layanan meliputi audit lingkungan, penyusunan Sistem Manajemen Lingkungan ISO 14001, pelatihan personil lingkungan, pemantauan kualitas lingkungan (air, udara, kebisingan), penyusunan laporan lingkungan berkala, dan pendampingan inspeksi dari dinas lingkungan hidup. Kami membantu perusahaan tidak hanya comply dengan regulasi, tetapi juga membangun reputasi sebagai perusahaan yang bertanggung jawab terhadap lingkungan.',
        'icon' => 'fa-user-tie',
        'color' => '#057642',
        'meta_keywords' => 'konsultan lingkungan, environmental consultant, iso 14001, manajemen lingkungan',
        'key_features' => [
            'Audit kepatuhan lingkungan oleh auditor berpengalaman',
            'Pendampingan implementasi ISO 14001 dari gap analysis hingga sertifikasi',
            'Pelatihan & capacity building personil lingkungan perusahaan',
            'Pemantauan kualitas air, udara, dan kebisingan',
            'Penyusunan laporan lingkungan berkala (RKL-RPL, PROPER)',
            'Pendampingan inspeksi reguler dari Dinas Lingkungan Hidup',
        ],
        'documents_required' => [
            'Dokumen lingkungan yang berlaku (AMDAL/UKL-UPL)',
            'Data operasional perusahaan (produksi, limbah, energi)',
            'Laporan pemantauan lingkungan sebelumnya',
            'Akses ke fasilitas & area produksi',
            'Struktur organisasi & penanggungjawab lingkungan',
            'Dokumen SOP pengelolaan lingkungan (jika ada)',
        ],
        'process_steps_detail' => [
            ['title' => 'Diskusi Kebutuhan', 'desc' => 'Identifikasi kebutuhan konsultasi: audit, ISO, pelatihan, atau monitoring.'],
            ['title' => 'Penugasan Tim Ahli', 'desc' => 'Tim konsultan ditugaskan sesuai spesialisasi dan kebutuhan klien.'],
            ['title' => 'Asesmen & Pengumpulan Data', 'desc' => 'Kunjungan lapangan, review dokumen, dan identifikasi gap kepatuhan.'],
            ['title' => 'Analisis & Penyusunan Rekomendasi', 'desc' => 'Evaluasi temuan dan penyusunan rencana aksi perbaikan.'],
            ['title' => 'Implementasi & Pendampingan', 'desc' => 'Pendampingan pelaksanaan rekomendasi dan persiapan sertifikasi/audit.'],
            ['title' => 'Pelaporan & Follow-up', 'desc' => 'Laporan final dan dukungan berkelanjutan pasca-penugasan.'],
        ],
        'sub_services' => [
            'audit-lingkungan' => [
                'title' => 'Audit Lingkungan',
                'short_description' => 'Audit komprehensif kepatuhan lingkungan perusahaan terhadap regulasi dan standar yang berlaku.',
                'long_description' => 'Audit lingkungan adalah evaluasi sistematis terhadap pengelolaan lingkungan perusahaan untuk memastikan kepatuhan terhadap peraturan perundang-undangan, dokumen lingkungan (AMDAL/UKL-UPL), dan standar internal perusahaan. Audit mencakup pengelolaan air limbah, emisi udara, limbah padat/B3, kebisingan, penggunaan energi, dan tata kelola lingkungan secara keseluruhan. Hasil audit berupa laporan temuan dan rekomendasi perbaikan.',
                'icon' => 'fa-search',
                'meta_keywords' => 'audit lingkungan, environmental audit, kepatuhan lingkungan, compliance audit',
                'process_steps' => ['Perencanaan & ruang lingkup audit', 'Pengumpulan data & dokumen', 'Inspeksi lapangan', 'Pengambilan sampel & pengujian', 'Evaluasi kepatuhan', 'Penyusunan laporan & rekomendasi'],
                'requirements' => ['Akses ke fasilitas & dokumen', 'Dokumen lingkungan yang berlaku', 'Data operasional perusahaan'],
                'duration' => '14-30 Hari',
            ],
            'iso-14001' => [
                'title' => 'Implementasi ISO 14001',
                'short_description' => 'Pendampingan implementasi Sistem Manajemen Lingkungan ISO 14001 hingga sertifikasi.',
                'long_description' => 'ISO 14001 adalah standar internasional untuk Sistem Manajemen Lingkungan (SML) yang membantu organisasi mengelola dampak lingkungannya secara sistematis. Kami mendampingi mulai dari gap analysis, penyusunan kebijakan lingkungan, identifikasi aspek & dampak lingkungan, penetapan tujuan & sasaran, penyusunan prosedur & dokumentasi, pelatihan personil, internal audit, hingga pendampingan audit sertifikasi oleh badan sertifikasi terakreditasi.',
                'icon' => 'fa-certificate',
                'meta_keywords' => 'iso 14001, sistem manajemen lingkungan, sertifikasi iso 14001, sml, environmental management',
                'process_steps' => ['Gap analysis', 'Penyusunan kebijakan & prosedur', 'Identifikasi aspek & dampak lingkungan', 'Pelatihan personil', 'Implementasi & monitoring', 'Internal audit', 'Pendampingan audit sertifikasi'],
                'requirements' => ['Komitmen manajemen puncak', 'Tim lingkungan internal', 'Data aspek & dampak lingkungan', 'Sumber daya implementasi'],
                'duration' => '4-6 Bulan',
            ],
            'pelatihan-lingkungan' => [
                'title' => 'Pelatihan & Capacity Building Lingkungan',
                'short_description' => 'Program pelatihan personil lingkungan perusahaan untuk meningkatkan kompetensi pengelolaan lingkungan.',
                'long_description' => 'Program pelatihan lingkungan mencakup pelatihan operator IPAL, pengelolaan limbah B3, tanggap darurat tumpahan B3, audit lingkungan internal, kesadaran lingkungan (environmental awareness), dan pelaporan lingkungan. Pelatihan disesuaikan dengan kebutuhan spesifik perusahaan dan regulasi yang berlaku.',
                'icon' => 'fa-chalkboard-teacher',
                'meta_keywords' => 'pelatihan lingkungan, training lingkungan, pelatihan ipal, pelatihan limbah b3',
                'process_steps' => ['Asesmen kebutuhan pelatihan', 'Penyusunan kurikulum', 'Pelaksanaan pelatihan (teori & praktik)', 'Evaluasi peserta', 'Penerbitan sertifikat pelatihan'],
                'requirements' => ['Peserta minimal 10 orang', 'Ruangan pelatihan', 'Akses ke fasilitas (untuk praktik lapangan)'],
                'duration' => '2-5 Hari',
            ],
        ],
        'faq' => [
            ['q' => 'Apa manfaat menggunakan jasa konsultan lingkungan?', 'a' => 'Konsultan lingkungan membantu memastikan kepatuhan regulasi, menghindari sanksi, mengoptimalkan pengelolaan limbah, dan membangun reputasi perusahaan yang bertanggung jawab.'],
            ['q' => 'Berapa biaya konsultasi lingkungan?', 'a' => 'Biaya bervariasi tergantung ruang lingkup. Audit lingkungan mulai Rp 15 juta, implementasi ISO 14001 mulai Rp 50 juta. Hubungi kami untuk penawaran spesifik.'],
            ['q' => 'Apakah ISO 14001 wajib?', 'a' => 'ISO 14001 tidak wajib secara hukum, namun banyak menjadi persyaratan tender proyek, supply chain requirement, dan membantu meningkatkan daya saing perusahaan.'],
        ],
    ],
    'monitoring-digital' => [
        'title' => 'Monitoring Lingkungan Digital',
        'slug' => 'monitoring-digital',
        'short_description' => 'Sistem pemantauan kualitas lingkungan real-time berbasis IoT',
        'category' => 'TEKNOLOGI',
        'price_range' => 'Mulai Rp 100 Jt',
        'process_time' => '30-60 Hari',
        'long_description' => 'Sistem Pemantauan Emisi dan Limbah Cair Online (SPARING) adalah kewajiban untuk industri tertentu sesuai Permen LHK No. 80 Tahun 2019. Sistem monitoring digital menggunakan sensor IoT untuk memantau parameter lingkungan (COD, BOD, pH, TSS untuk air limbah; SO2, NOx, partikulat untuk emisi udara) secara real-time dan mengirimkan data langsung ke server Kementerian Lingkungan Hidup. Kami menyediakan solusi lengkap mulai dari instalasi perangkat monitoring, kalibrasi sensor, koneksi ke sistem SPARING Kementerian LHK, hingga pelatihan operator dan maintenance berkala.',
        'icon' => 'fa-chart-line',
        'color' => '#6366F1',
        'meta_keywords' => 'monitoring lingkungan, sparing, iot monitoring, kualitas air online',
        'key_features' => [
            'Instalasi sistem SPARING sesuai Permen LHK No. 80/2019',
            'Sensor IoT untuk monitoring air limbah & emisi udara real-time',
            'Koneksi langsung ke server Kementerian LHK',
            'Dashboard monitoring real-time dengan alert otomatis',
            'Kalibrasi sensor berkala & maintenance preventif',
            'Pelatihan operator & SOP penggunaan sistem',
        ],
        'documents_required' => [
            'PERTEK Pembuangan Air Limbah atau Emisi',
            'Dokumen lingkungan (AMDAL/UKL-UPL)',
            'Layout titik sampling yang memenuhi standar',
            'Data parameter yang dipantau & baku mutu',
            'Akses ke sumber listrik stabil & internet',
            'Data teknis outlet air limbah / cerobong emisi',
        ],
        'process_steps_detail' => [
            ['title' => 'Asesmen Kebutuhan', 'desc' => 'Survey lokasi, identifikasi parameter wajib pantau, dan desain sistem.'],
            ['title' => 'Pengadaan Perangkat', 'desc' => 'Pemilihan dan pengadaan sensor, data logger, dan perangkat pendukung.'],
            ['title' => 'Instalasi & Konfigurasi', 'desc' => 'Pemasangan perangkat, konfigurasi data logger, konektivitas server.'],
            ['title' => 'Koneksi ke KLHK', 'desc' => 'Integrasi data ke server KLHK sesuai protokol SPARING.'],
            ['title' => 'Komisioning & Pelatihan', 'desc' => 'Kalibrasi, uji coba sistem, dan pelatihan operator internal.'],
        ],
        'sub_services' => [
            'sparing' => [
                'title' => 'SPARING (Pemantauan Online)',
                'short_description' => 'Instalasi dan pengelolaan Sistem Pemantauan Kualitas Air Limbah & Emisi Online sesuai Permen LHK.',
                'long_description' => 'SPARING (Sistem Pemantauan Kualitas Air Limbah Secara Terus Menerus dan Dalam Jaringan) adalah kewajiban bagi industri yang membuang air limbah ke badan air dan/atau melepaskan emisi ke udara sesuai Permen LHK No. 80/2019. Sistem ini mencakup sensor online (pH, COD, TSS, debit untuk air limbah; opacity, SO2, NOx untuk emisi), data logger, dan koneksi real-time ke server KLHK.',
                'icon' => 'fa-wifi',
                'meta_keywords' => 'sparing, pemantauan online, monitoring air limbah online, monitoring emisi online, permen lhk 80',
                'process_steps' => ['Asesmen kebutuhan monitoring', 'Pemilihan & pengadaan sensor', 'Instalasi perangkat monitoring', 'Konfigurasi data logger & konektivitas', 'Koneksi ke server KLHK', 'Kalibrasi & komisioning', 'Pelatihan operator'],
                'requirements' => ['PERTEK Pembuangan Air Limbah/Emisi', 'Titik sampling yang memenuhi standar', 'Sumber listrik stabil', 'Koneksi internet'],
                'duration' => '30-60 Hari',
            ],
            'dashboard-monitoring' => [
                'title' => 'Dashboard Monitoring Real-time',
                'short_description' => 'Platform dashboard digital untuk visualisasi, analitik, dan pelaporan data pemantauan lingkungan.',
                'long_description' => 'Dashboard monitoring kami menyediakan visualisasi data pemantauan lingkungan secara real-time dengan fitur alert otomatis saat parameter mendekati atau melampaui baku mutu. Dashboard mencakup grafik tren, histori data, analitik prediktif, dan generator laporan otomatis untuk pelaporan ke DLHK.',
                'icon' => 'fa-desktop',
                'meta_keywords' => 'dashboard monitoring lingkungan, monitoring real-time, analitik lingkungan, pelaporan otomatis',
                'process_steps' => ['Konfigurasi dashboard', 'Integrasi sensor & data source', 'Setting alert & threshold', 'Pelatihan pengguna', 'Maintenance berkala'],
                'requirements' => ['Perangkat monitoring terinstal', 'Koneksi internet stabil', 'Data parameter baku mutu'],
                'duration' => '7-14 Hari',
            ],
        ],
        'faq' => [
            ['q' => 'Apa itu SPARING dan siapa yang wajib?', 'a' => 'SPARING adalah sistem pemantauan online untuk air limbah dan emisi udara. Wajib bagi industri yang termasuk dalam Lampiran Permen LHK No. 80/2019, antara lain industri rayon, pulp/kertas, petrokimia, kelapa sawit, dan PLTU batubara.'],
            ['q' => 'Berapa biaya instalasi sistem monitoring?', 'a' => 'Biaya tergantung jumlah parameter, titik monitoring, dan jenis sensor. Kisaran mulai Rp 100 juta untuk sistem dasar. Hubungi kami untuk penawaran detail.'],
            ['q' => 'Apakah tersedia maintenance berkala?', 'a' => 'Ya, kami menyediakan paket maintenance bulanan/tahunan mencakup kalibrasi sensor, penggantian reagen, dan pemeliharaan perangkat.'],
        ],
    ],
    'izin-k3' => [
        'title' => 'Izin K3 (Keselamatan & Kesehatan Kerja)',
        'slug' => 'izin-k3',
        'short_description' => 'Pengurusan izin K3, PRTK, dan audit sistem manajemen keselamatan kerja',
        'long_description' => 'Keselamatan dan Kesehatan Kerja (K3) adalah kewajiban setiap perusahaan sesuai UU No. 1 Tahun 1970 tentang Keselamatan Kerja. Perusahaan dengan risiko tinggi wajib memiliki berbagai izin K3 seperti Pengesahan Rencana Teknis K3 (PRTK) untuk instalasi/mesin berbahaya, izin operasi pesawat angkat/angkut, izin instalasi listrik, dan sertifikasi operator alat berat. Kami membantu penyusunan dokumen teknis K3, koordinasi dengan Dinas Tenaga Kerja, pendampingan inspeksi petugas K3, serta implementasi Sistem Manajemen K3 (SMK3) untuk menciptakan lingkungan kerja yang aman dan produktif.',
        'icon' => 'fa-hard-hat',
        'color' => '#EF4444',
        'meta_keywords' => 'izin k3, keselamatan kerja, prtk, audit k3, smk3',
        'category' => 'K3',
        'price_range' => 'Mulai Rp 10 Jt',
        'process_time' => '7 Hari - 6 Bulan',
        'key_features' => [
            'Pengurusan PRTK untuk boiler, crane, forklift & instalasi berbahaya',
            'Pendampingan implementasi SMK3 sesuai PP No. 50/2012',
            'Audit & inspeksi K3 oleh ahli bersertifikat',
            'Penyusunan dokumen P2K3 dan program K3 perusahaan',
            'Koordinasi dengan Disnaker untuk pengesahan & sertifikasi',
            'Pelatihan K3 untuk pekerja dan manajemen',
        ],
        'documents_required' => [
            'Akta pendirian & profil perusahaan',
            'NIB & izin operasional',
            'Spesifikasi teknis peralatan/instalasi',
            'Gambar rencana teknis (untuk PRTK)',
            'Data jumlah pekerja & struktur organisasi K3',
            'Dokumen SOP K3 yang ada (jika sudah tersedia)',
            'Sertifikat material/komponen peralatan',
        ],
        'process_steps_detail' => [
            ['title' => 'Assessment K3 Awal', 'desc' => 'Identifikasi kebutuhan izin K3 berdasarkan jenis usaha dan peralatan.'],
            ['title' => 'Penyusunan Dokumen Teknis', 'desc' => 'Gambar teknis, SOP, prosedur, dan dokumen P2K3 disiapkan.'],
            ['title' => 'Pengajuan ke Disnaker', 'desc' => 'Submit permohonan ke Dinas Tenaga Kerja setempat.'],
            ['title' => 'Inspeksi & Pengujian', 'desc' => 'Pendampingan inspeksi petugas K3 dan pengujian peralatan.'],
            ['title' => 'Penerbitan Izin/Sertifikat', 'desc' => 'PRTK, izin operasi, atau sertifikat SMK3 terbit resmi.'],
        ],
        'sub_services' => [
            'prtk' => [
                'title' => 'PRTK (Pengesahan Rencana Teknis K3)',
                'short_description' => 'Pengurusan Pengesahan Rencana Teknis K3 untuk instalasi, mesin, dan peralatan berbahaya di tempat kerja.',
                'long_description' => 'PRTK (Pengesahan Rencana Teknis K3) diperlukan sebelum instalasi atau pengoperasian mesin, peralatan, dan instalasi yang memiliki potensi bahaya di tempat kerja. Meliputi: bejana tekan, ketel uap (boiler), pesawat angkat/angkut (crane, forklift), instalasi listrik tegangan tinggi, dan instalasi proteksi kebakaran. Tim kami menyusun dokumen teknis, gambar desain, dan koordinasi dengan Dinas Tenaga Kerja untuk pengesahan.',
                'icon' => 'fa-cog',
                'meta_keywords' => 'prtk, pengesahan rencana teknis k3, izin boiler, izin crane, inspeksi k3',
                'process_steps' => ['Identifikasi peralatan wajib PRTK', 'Penyusunan dokumen teknis', 'Pembuatan gambar rencana teknis', 'Pengajuan ke Disnaker', 'Pemeriksaan & pengujian', 'Pengesahan PRTK'],
                'requirements' => ['Spesifikasi teknis peralatan', 'Gambar rencana instalasi', 'Sertifikat material/komponen', 'PBG (untuk instalasi tetap)'],
                'duration' => '14-30 Hari',
            ],
            'smk3' => [
                'title' => 'SMK3 (Sistem Manajemen K3)',
                'short_description' => 'Pendampingan implementasi Sistem Manajemen K3 sesuai PP No. 50 Tahun 2012 hingga sertifikasi.',
                'long_description' => 'Sistem Manajemen Keselamatan dan Kesehatan Kerja (SMK3) wajib diterapkan oleh perusahaan dengan 100+ pekerja atau perusahaan berisiko tinggi sesuai PP No. 50 Tahun 2012. SMK3 mencakup: penetapan kebijakan K3, perencanaan, pelaksanaan, pemantauan, evaluasi, dan tinjauan manajemen. Kami mendampingi seluruh proses mulai dari gap analysis, penyusunan prosedur & dokumentasi, pelatihan P2K3, internal audit, hingga pendampingan audit eksternal untuk sertifikasi.',
                'icon' => 'fa-shield-alt',
                'meta_keywords' => 'smk3, sistem manajemen k3, pp 50 tahun 2012, sertifikasi smk3, audit smk3',
                'process_steps' => ['Gap analysis terhadap PP 50/2012', 'Penyusunan kebijakan & prosedur K3', 'Pembentukan & pelatihan P2K3', 'Implementasi program K3', 'Internal audit K3', 'Pendampingan audit sertifikasi'],
                'requirements' => ['Komitmen manajemen puncak', 'Tenaga ahli K3 umum (AK3U)', 'Data kecelakaan & near-miss', 'Identifikasi bahaya & penilaian risiko'],
                'duration' => '3-6 Bulan',
            ],
            'audit-k3' => [
                'title' => 'Audit & Inspeksi K3',
                'short_description' => 'Audit kepatuhan K3 dan pendampingan inspeksi petugas pengawas K3 dari Disnaker.',
                'long_description' => 'Layanan audit K3 mencakup evaluasi menyeluruh terhadap implementasi K3 di tempat kerja, identifikasi bahaya, penilaian risiko, dan verifikasi kepatuhan terhadap regulasi K3 yang berlaku. Kami juga mendampingi perusahaan saat inspeksi oleh petugas pengawas K3 dari Dinas Tenaga Kerja.',
                'icon' => 'fa-clipboard-check',
                'meta_keywords' => 'audit k3, inspeksi k3, kepatuhan k3, pengawas k3, safety audit',
                'process_steps' => ['Perencanaan ruang lingkup audit', 'Tinjauan dokumen K3', 'Inspeksi lapangan', 'Wawancara pekerja', 'Identifikasi temuan & rekomendasi', 'Penyusunan laporan audit K3'],
                'requirements' => ['Akses ke area kerja & dokumen K3', 'Data insiden & kecelakaan kerja', 'Daftar peralatan & instalasi'],
                'duration' => '7-14 Hari',
            ],
        ],
        'faq' => [
            ['q' => 'Apa itu PRTK dan kapan diperlukan?', 'a' => 'PRTK (Pengesahan Rencana Teknis K3) diperlukan sebelum instalasi/pengoperasian peralatan berbahaya: boiler, crane, forklift, instalasi listrik tegangan tinggi, dan bejana tekan.'],
            ['q' => 'Kapan perusahaan wajib menerapkan SMK3?', 'a' => 'SMK3 wajib bagi perusahaan dengan 100+ pekerja atau perusahaan yang memiliki tingkat potensi bahaya tinggi, sesuai PP No. 50 Tahun 2012.'],
            ['q' => 'Apa sanksi jika tidak memenuhi kewajiban K3?', 'a' => 'Sanksi meliputi teguran, denda administratif, penghentian operasi, pencabutan izin usaha. Untuk kecelakaan fatal akibat kelalaian K3, dapat dikenai sanksi pidana.'],
        ],
    ],
];
