<?php

return [
    'perizinan-lb3' => [
        'title' => 'Perizinan Limbah B3',
        'slug' => 'perizinan-lb3',
        'short_description' => 'Layanan lengkap perizinan Limbah Bahan Berbahaya & Beracun (B3) untuk industri',
        'icon' => 'fa-biohazard',
        'color' => '#DC2626',
        'meta_keywords' => 'perizinan lb3, limbah b3, izin limbah berbahaya, pengelolaan limbah b3',
    ],
    'amdal' => [
        'title' => 'AMDAL (Analisis Mengenai Dampak Lingkungan)',
        'slug' => 'amdal',
        'short_description' => 'Layanan penyusunan dokumen AMDAL untuk proyek berskala besar',
        'icon' => 'fa-leaf',
        'color' => '#059669',
        'meta_keywords' => 'amdal, analisis dampak lingkungan, dokumen amdal, konsultan amdal',
    ],
    'ukl-upl' => [
        'title' => 'UKL-UPL',
        'slug' => 'ukl-upl',
        'short_description' => 'Dokumen pengelolaan lingkungan untuk usaha skala menengah',
        'icon' => 'fa-file-alt',
        'color' => '#9333EA',
        'meta_keywords' => 'ukl upl, upaya kelola lingkungan, dokumen ukl upl, perizinan lingkungan',
    ],
    'oss-nib' => [
        'title' => 'OSS - NIB (Nomor Induk Berusaha)',
        'slug' => 'oss-nib',
        'short_description' => 'Pengurusan Nomor Induk Berusaha melalui sistem OSS',
        'icon' => 'fa-globe',
        'color' => '#F59E0B',
        'meta_keywords' => 'nib, nomor induk berusaha, oss, pengurusan nib, izin usaha',
    ],
    'pbg-slf' => [
        'title' => 'PBG / SLF',
        'slug' => 'pbg-slf',
        'short_description' => 'Perizinan bangunan dan sertifikat kelayakan fungsi gedung',
        'icon' => 'fa-building',
        'color' => '#0891B2',
        'meta_keywords' => 'pbg, slf, izin mendirikan bangunan, sertifikat laik fungsi',
    ],
    'izin-operasional' => [
        'title' => 'Izin Operasional Industri',
        'slug' => 'izin-operasional',
        'short_description' => 'Kelengkapan izin untuk operasional industri manufaktur',
        'icon' => 'fa-industry',
        'color' => '#EC4899',
        'meta_keywords' => 'izin operasional, izin industri, perizinan pabrik, compliance industri',
    ],
    'konsultan-lingkungan' => [
        'title' => 'Konsultan Lingkungan Hidup',
        'slug' => 'konsultan-lingkungan',
        'short_description' => 'Konsultasi dan pendampingan pengelolaan lingkungan perusahaan',
        'icon' => 'fa-user-tie',
        'color' => '#14B8A6',
        'meta_keywords' => 'konsultan lingkungan, environmental consultant, iso 14001, manajemen lingkungan',
    ],
    'monitoring-digital' => [
        'title' => 'Monitoring Lingkungan Digital',
        'slug' => 'monitoring-digital',
        'short_description' => 'Sistem pemantauan kualitas lingkungan real-time berbasis IoT',
        'icon' => 'fa-chart-line',
        'color' => '#6366F1',
        'meta_keywords' => 'monitoring lingkungan, sparing, iot monitoring, kualitas air online',
    ],
];
