<?php

/**
 * PMA (Foreign Investment) Services Configuration
 * 
 * Services specifically designed for foreign investors and multinational companies
 * operating in Indonesia. Pricing in USD, international standards compliance.
 */

return [
    'investment-registration' => [
        'title' => 'Investment Registration (BKPM)',
        'slug' => 'investment-registration',
        'short_description' => 'Foreign Direct Investment (PMA) approval and business license coordination through BKPM',
        'icon' => 'fa-handshake',
        'color' => '#1E40AF',
        'meta_keywords' => 'bkpm approval, pma registration, foreign investment indonesia, investment permit, fdi indonesia',
        'category' => 'INVESTMENT',
        'featured' => true,
        'pricing' => [
            'min' => 5000,
            'max' => 15000,
            'currency' => 'USD',
            'display' => 'USD 5,000 - 15,000',
        ],
        'duration' => '30-45 days',
        'long_description' => 'We handle the complete BKPM (Investment Coordinating Board) approval process for your foreign direct investment, ensuring full compliance with Indonesian investment regulations and sector-specific requirements. Our experienced team navigates the complex regulatory landscape to secure your investment principle approval efficiently. We manage all interactions with BKPM, relevant technical ministries, and sector regulators to streamline your investment journey in Indonesia.',
        'deliverables' => [
            'Investment principle approval from BKPM',
            'Business identification number (NIB) with business license',
            'Investment realization report (LKPM) setup and first submission',
            'Coordination with relevant sector ministries (Industry, Trade, Energy, etc.)',
            'Investment facility and incentive recommendations (tax holidays, import duty exemptions)',
            'Foreign ownership structure optimization advisory',
            'Negative investment list (DNI) compliance verification',
            'Capital requirement and realization roadmap',
        ],
        'requirements' => [
            'Parent company profile, corporate structure, and financial statements (last 2 years)',
            'Detailed business plan including market analysis and projected financials (5 years)',
            'Proof of capital availability (bank reference letter or audited financials)',
            'Shareholder and director identification documents (passports, KTP equivalents)',
            'Feasibility study for large-scale investments (>USD 25 million)',
            'Environmental clearance readiness assessment',
            'Proposed company name (minimum 3 options)',
            'Detailed product/service specifications and KBLI codes',
            'Land acquisition plan or lease agreement (if applicable)',
        ],
        'process_steps' => [
            'Initial consultation and investment assessment',
            'Document preparation and verification',
            'BKPM online system registration',
            'Application submission and follow-up',
            'Approval and NIB issuance',
        ],
    ],

    'company-establishment' => [
        'title' => 'Company Establishment (PT PMA)',
        'slug' => 'company-establishment',
        'short_description' => 'Complete PT PMA incorporation including notary deed, Ministry of Law approval, and all registrations',
        'icon' => 'fa-building',
        'color' => '#DC2626',
        'meta_keywords' => 'pt pma setup, company incorporation indonesia, business registration, foreign company indonesia',
        'category' => 'LEGAL',
        'featured' => true,
        'pricing' => [
            'min' => 3500,
            'max' => 8000,
            'currency' => 'USD',
            'display' => 'USD 3,500 - 8,000',
        ],
        'duration' => '14-30 days',
        'long_description' => 'End-to-end company establishment services for PT PMA (foreign investment company) including notary deed preparation, shareholder meeting minutes, Ministry of Law and Human Rights approval, and all necessary government registrations. We ensure your company is properly structured and compliant from day one. Our service covers complete corporate documentation, banking relationship establishment, and post-incorporation compliance setup.',
        'deliverables' => [
            'Notarized deed of establishment (bilingual: Indonesian + English)',
            'Ministry of Law and Human Rights decree and company registration number',
            'Company registration certificate (TDP equivalent through OSS)',
            'Articles of association and bylaws (Anggaran Dasar)',
            'Board resolution templates and meeting minute formats',
            'Corporate seal, stamps, and official documentation',
            'Company domicile letter (Surat Keterangan Domisili)',
            'Digital signature setup for directors',
            'Corporate bank account opening assistance',
            'Corporate governance manual and compliance checklist',
        ],
        'requirements' => [
            'Passport copies of all shareholders and directors (notarized)',
            'Company name options (minimum 3 choices, checked for availability)',
            'Proposed capital structure, shareholding percentages, and paid-up capital plan',
            'Registered office address proof (lease agreement or ownership certificate)',
            'Shareholder resolution authorizing establishment (if parent company)',
            'Curriculum vitae of directors and commissioners',
            'Director home address proof (for domicile registration)',
            'Bank reference letters for shareholders (if required)',
            'Apostille or legalization of foreign documents',
        ],
        'process_steps' => [
            'Company name reservation',
            'Drafting articles of association',
            'Notary deed signing',
            'Ministry of Law submission',
            'Company registration and seal creation',
        ],
    ],

    'tax-fiscal' => [
        'title' => 'Tax & Fiscal Registration',
        'slug' => 'tax-fiscal',
        'short_description' => 'NPWP, PKP (VAT) registration, and tax incentive applications for foreign investors',
        'icon' => 'fa-calculator',
        'color' => '#0891B2',
        'meta_keywords' => 'npwp registration, tax id indonesia, vat registration pkp, tax incentives indonesia',
        'category' => 'TAX',
        'pricing' => [
            'min' => 800,
            'max' => 2500,
            'currency' => 'USD',
            'display' => 'USD 800 - 2,500',
        ],
        'duration' => '7-14 days',
        'long_description' => 'Comprehensive tax registration and compliance setup including company and personal NPWP (Tax ID), PKP (VAT registration) for taxable enterprises, and strategic assessment of available tax incentives including tax holidays, investment allowances, and special economic zone benefits. We provide ongoing tax advisory to ensure optimal tax structuring and compliance with Indonesian tax regulations while maximizing available incentives for foreign investors.',
        'deliverables' => [
            'Company NPWP (Tax Identification Number) - permanent registration',
            'Director and expatriate staff NPWP (if required)',
            'PKP (Pengusaha Kena Pajak) VAT registration certificate',
            'Comprehensive tax incentive eligibility assessment and application strategy',
            'E-tax system (DJP Online) registration, digital certificate, and user training',
            'Tax calendar and obligation schedule for your company',
            'Withholding tax setup guide for international transactions',
            'Transfer pricing documentation requirements assessment',
            'Tax treaty benefits analysis (based on shareholder country)',
        ],
        'requirements' => [
            'Company establishment decree from Ministry of Law',
            'NIB (Business Identification Number) with business license',
            'Director passport, KITAS/work permit, and residential address in Indonesia',
            'Registered office address proof (lease or ownership)',
            'Company bank account details and opening statement',
            'Organizational structure and employee forecast',
            'Revenue and expense projections (for VAT threshold assessment)',
            'List of planned international transactions (for treaty benefits)',
        ],
        'process_steps' => [
            'Tax office registration',
            'NPWP application submission',
            'PKP assessment and application',
            'E-tax system setup',
            'Tax incentive consultation',
        ],
    ],

    'immigration-services' => [
        'title' => 'Immigration & Work Permits',
        'slug' => 'immigration-services',
        'short_description' => 'Complete immigration services: IMTA work permits, KITAS/KITAP residence permits, and expatriate compliance',
        'icon' => 'fa-passport',
        'color' => '#9333EA',
        'meta_keywords' => 'work permit indonesia, kitas, kitap, imta, expatriate visa, indonesia work visa',
        'category' => 'IMMIGRATION',
        'pricing' => [
            'min' => 1500,
            'max' => 4000,
            'currency' => 'USD',
            'display' => 'USD 1,500 - 4,000 per permit',
        ],
        'duration' => '14-21 days',
        'long_description' => 'Full immigration support for foreign employees and their families including work permit approval (IMTA), limited stay permits (KITAS), permanent stay permits (KITAP), visa processing, and ongoing compliance management. We handle all interactions with immigration authorities on your behalf, ensuring full compliance with Ministry of Manpower and Directorate General of Immigration regulations. Our service includes family member support and emergency travel document assistance.',
        'deliverables' => [
            'IMTA (work permit) approval letter from Ministry of Manpower',
            'KITAS (limited stay permit) for 1-2 years with multiple re-entry permit',
            'MERP (expatriate reporting) online registration',
            'DP5 (expatriate notification) and monthly manpower reporting',
            'RPTKA (expatriate employment plan) preparation if needed',
            'Renewal reminder and proactive management service',
            'Dependent visa and KITAS for family members',
            'Exit permit (EPO) processing when required',
            'Immigration compliance calendar and training',
        ],
        'requirements' => [
            'Passport with minimum 18 months validity',
            'Complete curriculum vitae and notarized educational certificates',
            'Employment contract or expatriate assignment letter',
            'Recent passport-size photograph (4x6cm, red background)',
            'Health insurance and life insurance certificates (minimum coverage requirements)',
            'Manpower compensation fund (DKPTKA) payment proof',
            'Position justification letter and local staff training plan',
            'Indonesian language proficiency certificate (for certain positions)',
            'Company IMTA quota allocation letter (if applicable)',
        ],
        'process_steps' => [
            'IMTA application to Ministry of Manpower',
            'Visa recommendation letter (VTT/LD)',
            'Visa on arrival or visa collection',
            'KITAS application and biometric data',
            'MERP and DP5 registration',
        ],
    ],

    'environmental-compliance' => [
        'title' => 'Environmental Compliance',
        'slug' => 'environmental-compliance',
        'short_description' => 'AMDAL/UKL-UPL environmental assessments aligned with international standards, ISO 14001 consultation',
        'icon' => 'fa-leaf',
        'color' => '#059669',
        'meta_keywords' => 'amdal indonesia, environmental permit, ukl upl, iso 14001, environmental compliance indonesia',
        'category' => 'ENVIRONMENT',
        'pricing' => [
            'min' => 8000,
            'max' => 50000,
            'currency' => 'USD',
            'display' => 'USD 8,000 - 50,000',
        ],
        'duration' => '60-180 days',
        'long_description' => 'Environmental impact assessment and permit processing following Indonesian environmental regulations while maintaining alignment with international best practices and corporate ESG standards. We provide AMDAL for high-impact projects and UKL-UPL for medium-impact operations, with ongoing environmental monitoring support. Our team includes certified environmental assessors and specialists across various industries ensuring credible, defensible documentation.',
        'deliverables' => [
            'AMDAL (Environmental Impact Assessment) or UKL-UPL document based on project scale',
            'Environmental permit (Izin Lingkungan) approval from provincial/national authorities',
            'Environmental management plan (RKL) and monitoring plan (RPL)',
            'ISO 14001 Environmental Management System readiness assessment',
            'Quarterly and annual environmental reporting templates and assistance',
            'Public consultation facilitation and documentation (for AMDAL)',
            'Environmental monitoring baseline study',
            'Waste management permit recommendations (B3 and non-B3)',
            'Carbon footprint assessment and ESG reporting framework',
        ],
        'requirements' => [
            'Detailed project technical specifications and production capacity',
            'Site location map, coordinates, and land ownership documents',
            'Process flow diagram, equipment list, and chemical inventory',
            'Waste generation estimates and disposal/treatment plan',
            'Emergency response and spill contingency procedures',
            'Water usage and wastewater treatment plan',
            'Air emissions sources and pollution control equipment specifications',
            'Noise, vibration, and odor impact assessment data',
            'Community and stakeholder mapping (for AMDAL)',
        ],
        'process_steps' => [
            'Environmental impact screening',
            'Baseline environmental study',
            'Public consultation (for AMDAL)',
            'Document preparation and submission',
            'Technical assessment and approval',
        ],
    ],

    'land-building' => [
        'title' => 'Land & Building Permits',
        'slug' => 'land-building',
        'short_description' => 'Land acquisition advisory, building permits (PBG), and safety certificates (SLF) for foreign investors',
        'icon' => 'fa-home',
        'color' => '#F59E0B',
        'meta_keywords' => 'land permit indonesia, building permit pbg, slf certificate, construction permit indonesia',
        'category' => 'PROPERTY',
        'pricing' => [
            'min' => 5000,
            'max' => 25000,
            'currency' => 'USD',
            'display' => 'USD 5,000 - 25,000',
        ],
        'duration' => '30-90 days',
        'long_description' => 'Comprehensive land acquisition advisory and building permit services tailored for foreign investors and property developers. We provide due diligence, land rights structuring options (including HGB for foreigners), building permit processing, and post-construction certification to ensure full legal compliance. Our legal team coordinates with National Land Agency (BPN), local planning authorities, and building inspectors throughout the process.',
        'deliverables' => [
            'Comprehensive land title due diligence and chain-of-ownership verification',
            'Land rights structuring advice (HGB, Hak Pakai, lease options for foreign entities)',
            'Building permit (PBG - Persetujuan Bangunan Gedung) approval',
            'Certificate of building worthiness (SLF - Sertifikat Laik Fungsi)',
            'Site plan approval (Rencana Tapak)',
            'Location permit and environmental clearance coordination',
            'Utility connection permits (electricity, water, gas)',
            'Construction timeline coordination and inspection scheduling',
            'Neighboring land owner notification and consent (if required)',
        ],
        'requirements' => [
            'Land certificate (Sertifikat Hak Milik/HGB) or proof of ownership/lease rights',
            'Complete architectural, structural, and MEP (mechanical, electrical, plumbing) building plans',
            'Structural calculations certified by licensed engineer',
            'Geotechnical/soil investigation report',
            'Environmental clearance certificate (UKL-UPL minimum)',
            'Site photos, topographic survey, and lot measurements',
            'Fire safety and emergency exit plan',
            'Construction method statement and timeline',
            'Contractor license and qualifications (for PBG application)',
        ],
        'process_steps' => [
            'Land title verification and due diligence',
            'Site plan and zoning clearance',
            'Building permit application',
            'Construction monitoring (optional)',
            'SLF certification after completion',
        ],
    ],

    'operational-licenses' => [
        'title' => 'Operational Licenses',
        'slug' => 'operational-licenses',
        'short_description' => 'Sector-specific operational permits, import/export licenses, and product registration services',
        'icon' => 'fa-certificate',
        'color' => '#EC4899',
        'meta_keywords' => 'operational license indonesia, import permit api, export license, sector-specific permits',
        'category' => 'OPERATIONS',
        'pricing' => [
            'min' => 2000,
            'max' => 15000,
            'currency' => 'USD',
            'display' => 'USD 2,000 - 15,000',
        ],
        'duration' => 'Varies by sector (14-90 days)',
        'long_description' => 'Specialized operational permits based on your business sector including manufacturing licenses, trading permits (import/export), service industry certifications, and product registration. We have deep expertise across various sectors including manufacturing, trading, logistics, F&B, pharmaceuticals, and technology. Our sector specialists navigate complex regulatory requirements across ministries including Trade, Industry, Health, Agriculture, Communications, and Financial Services Authority.',
        'deliverables' => [
            'Sector-specific operational license (Manufacturing, Trading, Services)',
            'Import identification number (API-U for general goods, API-P for producer)',
            'Product registration certificates (BPOM for food/drugs, Postel for electronics, etc.)',
            'Indonesian National Standard (SNI) certification support',
            'Halal certification facilitation (for F&B products)',
            'Factory operating permit (IUI - Izin Usaha Industri)',
            'Distribution license (SIUP equivalent through OSS)',
            'Customs clearance and bonded zone registration assistance',
            'Export license for restricted commodities',
        ],
        'requirements' => [
            'Company registration documents and NIB with appropriate KBLI codes',
            'Sector-specific business license showing operational eligibility',
            'Product technical specifications, formulations, and safety data sheets',
            'Quality management certificates (ISO 9001, HACCP, GMP, etc.)',
            'Facility layout, capacity documentation, and inspection readiness',
            'Import product samples (for product registration)',
            'Certificate of origin and export permits (for import items)',
            'Supplier agreements and manufacturing authorization letters',
            'Laboratory test results from accredited institutions',
        ],
        'process_steps' => [
            'Sector regulation assessment',
            'License requirement mapping',
            'Document preparation and submission',
            'Facility inspection coordination',
            'License issuance and activation',
        ],
    ],

    'ongoing-compliance' => [
        'title' => 'Ongoing Compliance & Support',
        'slug' => 'ongoing-compliance',
        'short_description' => 'Monthly retainer for permit renewals, annual reporting, regulatory updates, and compliance advisory',
        'icon' => 'fa-sync',
        'color' => '#14B8A6',
        'meta_keywords' => 'compliance retainer indonesia, permit renewal service, regulatory updates, annual reporting',
        'category' => 'COMPLIANCE',
        'featured' => true,
        'pricing' => [
            'min' => 500,
            'max' => 2000,
            'currency' => 'USD',
            'display' => 'USD 500 - 2,000/month',
        ],
        'duration' => 'Ongoing (monthly retainer)',
        'long_description' => 'Dedicated compliance support ensuring all permits stay current and your business remains fully compliant with evolving Indonesian regulations. Our retainer service includes proactive permit renewal management, annual statutory reporting, regulatory change monitoring, and priority access to our advisory team.',
        'deliverables' => [
            'Automated permit renewal management',
            'Annual reporting assistance (tax, BKPM, etc.)',
            'Monthly regulatory change alerts',
            'Quarterly compliance health check',
            'Priority support and consultation access',
        ],
        'requirements' => [
            'Complete list of existing permits',
            'Company compliance calendar',
            'Designated primary contact person',
            'Access to company documents (secure portal)',
        ],
        'process_steps' => [
            'Initial compliance audit and documentation',
            'Setup of renewal calendar and alerts',
            'Monthly monitoring and reporting',
            'Proactive renewal processing',
            'Continuous regulatory advisory',
        ],
    ],

    'intellectual-property' => [
        'title' => 'Intellectual Property Protection',
        'slug' => 'intellectual-property',
        'short_description' => 'Trademark, patent, copyright registration and IP protection strategies for foreign companies in Indonesia',
        'icon' => 'fa-shield-alt',
        'color' => '#6366F1',
        'meta_keywords' => 'trademark registration indonesia, patent indonesia, copyright protection, ip registration',
        'category' => 'LEGAL',
        'pricing' => [
            'min' => 1200,
            'max' => 8000,
            'currency' => 'USD',
            'display' => 'USD 1,200 - 8,000',
        ],
        'duration' => '30-180 days',
        'long_description' => 'Comprehensive intellectual property registration and protection services through the Indonesian Directorate General of Intellectual Property (DJKI). We handle trademark registration, patent applications, copyright protection, and develop strategic IP protection plans aligned with your business objectives. Our experienced team ensures your intellectual assets are properly secured in Indonesia\'s regulatory framework.',
        'deliverables' => [
            'Trademark registration certificate (for brands, logos)',
            'Patent registration (for inventions and innovations)',
            'Copyright registration (for creative works)',
            'IP conflict search and clearance report',
            'IP protection strategy document',
            'Opposition and enforcement advisory',
        ],
        'requirements' => [
            'Company registration documents',
            'Trademark specimens or logo files (high resolution)',
            'Patent technical specifications and drawings',
            'Proof of prior use or creation date',
            'Power of attorney (notarized)',
            'Description of goods/services (for trademarks)',
        ],
        'process_steps' => [
            'IP portfolio audit and strategy consultation',
            'Comprehensive conflict search and analysis',
            'Application preparation and filing with DJKI',
            'Examination monitoring and response',
            'Publication and opposition period management',
            'Certificate issuance and maintenance',
        ],
        'compliance_notes' => [
            'Trademark protection lasts 10 years (renewable)',
            'Patents protected for 20 years from filing date',
            'Copyright automatic but registration provides legal advantage',
            'Madrid Protocol available for international trademark registration',
            'Patent Cooperation Treaty (PCT) applicable for patents',
        ],
    ],
];

